### PR TITLE
Limit path to HESTIA_CMD dir only

### PR DESCRIPTION
**Pull request by jaapmarcus**

### CODE REVIEW

**Comment by divinity76** [comment]
actually the slash should be part of the check so it cant be fooled into running something from a different dir whose name starts with the same name as HESTIA_CMD 's basename, for example $cmd could be `../hestiacmd_libs/something`  and HESTA_CMD could be `/hestiacmd` and `realpath("/hestiacmd/../hestiacmd_libs/something")`  would still match `/hestiacmd`  but it wouldn't match `/hestiacmd/`  so the code should be
```
if( 0 !==strpos($cli_script, HESTIA_CMD."/" )){
```
but since PHP8 we can use str_starts_with, so the code should be
```
if(!str_starts_with($cli_script, HESTIA_CMD."/" )){
```
but even after we have confirmed that the realpath is actually inside HESTIA_CMD/ , we still need to escape the argument in case the executable has newlines in the filepath (extremely rare, but it IS legal in linux filenames to have newlines in the filename, and forgetting this fact can sometimes lead to shell injection vulnerabilities), so the code should be:
```
        $cli_script = realpath(HESTIA_CMD . '/' . $cmd);
        if(!str_starts_with($cli_script, HESTIA_CMD."/" )){
            trigger_error("$cmd is trying to traverse outside of $HESTIA_CMD");
            throw new \Exception("$cmd is trying to traverse outside of $HESTIA_CMD");   
        }
        $cli_script = escapeshellarg($cli_script);
```
but we forgot that realpath will return bool(false) if $cmd does not exist, so the code should be:
```
        $cli_script = realpath(HESTIA_CMD . '/' . $cmd);
        if(!str_starts_with((string)$cli_script, HESTIA_CMD."/" )){
            trigger_error("$cmd is trying to traverse outside of $HESTIA_CMD");
            throw new \Exception("$cmd is trying to traverse outside of $HESTIA_CMD");   
        }
        $cli_script = escapeshellarg($cli_script);
```
but we also forgot that HESTIA_CMD is a constant, not a variable, so the code should actually be:
```
        $cli_script = realpath(HESTIA_CMD . '/' . $cmd);
        if(!str_starts_with((string)$cli_script, HESTIA_CMD."/" )){
            trigger_error("$cmd is trying to traverse outside of " .HESTIA_CMD);
            throw new \Exception("$cmd is trying to traverse outside of " . HESTIA_CMD);   
        }
        $cli_script = escapeshellarg($cli_script);
```
but it's easier to maintain if written as
```
        $cli_script = realpath(HESTIA_CMD . '/' . $cmd);
        if(!str_starts_with((string)$cli_script, HESTIA_CMD."/" )){
            $errstr = "$cmd is trying to traverse outside of " .HESTIA_CMD;
            trigger_error($errstr);
            throw new \Exception($errstr);   
        }
        $cli_script = escapeshellarg($cli_script);
```
btw can you explain why we're both calling trigger_error and throwing?

**Comment by jaapmarcus** [comment]
Current exception doesn't log currently in php log files and it makes debugging in cases more difficult

https://github.com/hestiacp/hestiacp/blob/18adc9541067a5a4d734fae54be86dc6da56fca1/web/add/webapp/index.php#L58-L61

We should expand the exception to do the logging

**Review by divinity76 — APPROVED** [review]
LGTM.

**Comment by divinity76** [comment]
> Current exception doesn't log currently in php log files and it makes debugging in cases more difficult
> 
> https://github.com/hestiacp/hestiacp/blob/18adc9541067a5a4d734fae54be86dc6da56fca1/web/add/webapp/index.php#L58-L61
> 
> We should expand the exception to do the logging

easy, just replace `exit();`  with `throw $e;`   - btw pretty sure it should be
```
 } catch (Exception $e) { 
     // http_response_code(500);
     $_SESSION['error_msg'] = $e->getMessage(); 
     header('Location: /add/webapp/?domain=' . $v_domain); 
     throw $e;
```

btw in Javascript, a long time ago i used to call both events and errors for e, this lead to naming collisions like
```
function eventHandler(e){
    try{
        (something that can throw here)
     } catch(e){
         // oops! accidentally overwritten Event e with Error e !
     }
}
```
and that is why i usually call my exceptions for ex  and events for ev (or $ex and $ev if you will) - if you're also a javascript developer, i recommend picking up the habit of calling exceptions for ex ^^

**Pull request merged**
