### PR TITLE
Unavailable IP List removed

### PR DESCRIPTION
**Pull request by EmrahKayihan**

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Can confirm the issue with http://danger.rulez.sk/projects/bruteforceblocker/blist.php is removed when visiting the url: service unavailable

Added removal for current installs

**Comment by Lupul** [comment]
The list looks to be fine, probably there was a temporary isuue

image

**Comment by jaapmarcus** [comment]
Still have issues:
Screenshot 2021-05-24 at 08 04 01

**Comment by myrevery** [comment]
I used the HttpHead tool to test this URL for two days, and there was no access failure in 180+ locations around the world.

After investigation, it seems that the DNS response failure in some areas was caused by Hetzner's network failure.

This should be considered a temporary error. 

Tools used: https://tools.ipip.net/httphead.php

**Pull request merged**
