### PR TITLE
[Fix] - css issue in spinner coundown

### PR DESCRIPTION
**Pull request by gejobj**
Added clip-path to .spinner css class to make mask compatible with Firefox.

### CODE REVIEW

**Comment by gejobj** [comment]
Hi!
I added "clip-path:ellipse(10px 10px at 50% 50%);" to .spinner class to make it compatible with firefox.
Best regards.

**Comment by jaapmarcus** [comment]
Please also update https://github.com/hestiacp/hestiacp/blob/main/web/css/src/themes/default.css

**Comment by gejobj** [comment]
Sorry, I make a new pull request: https://github.com/hestiacp/hestiacp/pull/2162
Thanks!

**Comment by jaapmarcus** [comment]
Both files need to be updated :) 

But anyway thanks

**Comment by gejobj** [comment]
> Both files need to be updated :)
> 
> But anyway thanks

oks, sorry.
I thought I changed the wrong file so I created a new pull request.
Thanks :-)

**Comment by jaapmarcus** [comment]
We usually minify css files as it is easier to modify/read if needed. Without the changes it will be lost when we update the css file again...

**Pull request merged**
