### PR TITLE
Update default.css

### PR DESCRIPTION
**Pull request by chriscapisce**
Make long passwords as displayed in .mail-infoblock break-word to fit div.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Please also update web/css/themes/default.min.css

**Comment by chriscapisce** [comment]
> Please also update web/css/themes/default.min.css

I did..?

**Comment by jaapmarcus** [comment]
You did add it to the main branch in your fork:

https://github.com/chriscapisce/hestiacp/commit/df4c30582c4e4f1eef69a5bdaf3d3d027840be76

I have merged it in to this branch

**Comment by chriscapisce** [comment]
> Please also update web/css/themes/default.min.css
I did, but not commit perhaps?

**Comment by chriscapisce** [comment]
> You did add it to the main branch in your fork:
> 
> [chriscapisce@df4c305](https://github.com/chriscapisce/hestiacp/commit/df4c30582c4e4f1eef69a5bdaf3d3d027840be76)
> 
> I have merged it in to this branch

Thanks, still learning to work with Github.

**Comment by jaapmarcus** [comment]
It was committed to the main branch :) in your fork.  

I did allready fixed it  by cherrypicking it

**Comment by chriscapisce** [comment]
> settings

Thank you!

**Pull request merged**
