### PR TITLE
Create v-install-wordpress

### PR DESCRIPTION
**Pull request by mawaki**
Install WordPress from CLI or API. It needs check_if_database_exists() and generate_password() to be in /usr/local/hestia/db.sh it also needs the following file: /usr/local/hestia/func/handle_parameters.sh. All of these have been proposed too.

### CODE REVIEW

**Review by mawaki — COMMENTED** [review]
Looks good

**Comment by adion-gorani** [comment]
Why do not use: v-add-user-wp-cli i think is more secure.

https://github.com/hestiacp/hestiacp/blob/release/bin/v-add-user-wp-cli

**Comment by mawaki** [comment]
It is not straightforward. You will have to create a database first, and
then install WordPress, while this command (v-install-wordpress) will do
everything for you in one request (like when you install it on the web ui).

**Comment by adion-gorani** [comment]
No i mean in this part of the code you install wp-cli in /usr/local/bin


if [ ! -f "/usr/local/bin/wp" ]; then
    echo "=== Downloading latest wp-cli"
    wget -nv https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -O /usr/local/bin/wp
    chmod +x /usr/local/bin/wp
fi


With v-add-user-wp-cli you install it on the user folder and you can call it with v-run-cli-cmd username wp

**Comment by mawaki** [comment]
Yes, that could also work.

**Comment by jaapmarcus** [comment]
> Looks good

I only merged the 3 PR into 1 PR to make it easier to code review ...

**Comment by jaapmarcus** [comment]
Closed for in favour for:

https://github.com/hestiacp/hestiacp/pull/4443

**Pull request closed without merging**
