### PR TITLE
added $no-cache as a map in cachemap.conf under /nginx/conf/ and updated installers

### PR DESCRIPTION
**Pull request by ghost**
added $no-cache as a map in cachemap.conf under /nginx/conf/ as it must be under http block. It is the best way to do this vs using IF.  Updated the installer to place the file and updated the cache templates. Firstime contributing please forgive if I have made a mistake in my process but the code is totally good!

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
map file for no-cache instead of using if

**Comment by ioannidesalex** [comment]
Good idea. However this implementation covers only Nginx+Apache configurations. Nginx also doesn’t load (include) cahemap.conf by default (unless that’s what we want). Also needs to cover current installations as well (upgrades).

**Comment by ghost** [comment]
> Good idea. However this implementation covers only Nginx+Apache configurations. Nginx also doesn’t load (include) cahemap.conf by default (unless that’s what we want). Also needs to cover current installations as well (upgrades).

The directory it is located is set in nginx.conf to load all files with endings of conf (include /etc/nginx/conf.d/*.conf;) end of nginx.con. Also, it supports Nginx/Apache... It can't support apache as it has no Nginx cache... As for Nginx alone... there is no cache template but this uses the $no_cache so I could update all templates for FastCGI cache as well and add anything particular to them. but not going to do that unless I know its wanted and would be used... 

But wanted to get it out for the most popular used template as Nginx.org themselves say IF is evil and don't use it.

**Comment by jaapmarcus** [comment]
> > Good idea. However this implementation covers only Nginx+Apache configurations. Nginx also doesn’t load (include) cahemap.conf by default (unless that’s what we want). Also needs to cover current installations as well (upgrades).
> 
> The directory it is located is set in nginx.conf to load all files with endings of conf (include /etc/nginx/conf.d/*.conf;) end of nginx.con. Also, it supports Nginx/Apache... It can't support apache as it has no Nginx cache... As for Nginx alone... there is no cache template but this uses the $no_cache so I could update all templates for FastCGI cache as well and add anything particular to them. but not going to do that unless I know its wanted and would be used...

Just to make it more clear... 

We have to different setups: 
Nginx + Apache2
And Nginx "Standalone" 
And older servers only Apache2 only.. 

The suggested changes only for for the first case "Nginx + Apache2" and currently not for the Nginx standalone "users" 

For Nginx "Stanalone" mode it will be more work as we have to rewrite each use case.  

 I think the changes look fine we only need to implement an upgrade script in /usr/local/hestia/install/upgrade/versions/x.x.sh

**Comment by ghost** [comment]
> > > Good idea. However this implementation covers only Nginx+Apache configurations. Nginx also doesn’t load (include) cahemap.conf by default (unless that’s what we want). Also needs to cover current installations as well (upgrades).
> > 
> > 
> > The directory it is located is set in nginx.conf to load all files with endings of conf (include /etc/nginx/conf.d/*.conf;) end of nginx.con. Also, it supports Nginx/Apache... It can't support apache as it has no Nginx cache... As for Nginx alone... there is no cache template but this uses the $no_cache so I could update all templates for FastCGI cache as well and add anything particular to them. but not going to do that unless I know its wanted and would be used...
> 
> Just to make it more clear...
> 
> We have to different setups:
> Nginx + Apache2
> And Nginx "Standalone"
> And older servers only Apache2 only..
> 
> The suggested changes only for for the first case "Nginx + Apache2" and currently not for the Nginx standalone "users"
> 
> For Nginx "Stanalone" mode it will be more work as we have to rewrite each use case.
> 
> I think the changes look fine we only need to implement an upgrade script in /usr/local/hestia/install/upgrade/versions/x.x.sh

You wouldn't have proxy cache in standalone nginx.. instead fast cgi. If it's standalone has nothing to proxy to.

**Comment by ghost** [comment]
I can put the map in the cache.sh of the template. And set it only to write that particular file if that templates being used. That would completely separate it from standalone

**Comment by ScIT-Raphael** [comment]
Hi, thank you for your PR - as you may noticed, it wasnt merged for a long time because there was a discussion "do we want to implement it or not", including multiple reviews where we either decided to "not yet" or "lets check it later". We did now another review round and decided to close your PR and not implement the change. We appreciate your work and effor, but we do not see a need to implement the related change.

**Pull request closed without merging**
