### PR TITLE
MVP ESLint

### PR DESCRIPTION
**Pull request by AlecRust**
We will eventually need a package.json for front end tooling, I assume in "/web". ESLint is a good place to start.

This PR adds a package.json and basic ESLint setup, mainly to open discussion around how this will be done.

Questions:
- **Where to lint?**
  I've added a basic Drone job for ESLint in this PR, but Drone is slow/one build at a time. Front end linting could instead run with GitHub Actions ([example](https://github.com/actions/starter-workflows/blob/main/code-scanning/eslint.yml)) which would be faster and allow features like commenting on specific lines etc.
- **How to release?**
  I'm don't know Hestia's release process, but the "version" in package.json should be probably match the current Hestia version. Out of scope for this PR, but when JS/CSS is built via this e.g. "yarn build" will need to be part of release too.

---

relates to #2798

### CODE REVIEW

**Comment by imjuniper** [comment]
I'm personally a bit of a prettier fan (that way I don't need to worry about formatting haha), so I'd suggest adding prettier to this setup.

It would require adding 2 `devDependencies`: `eslint-config-prettier` and `prettier`.
We could change the scripts to this:
```json
"lint": "prettier --plugin-search-dir . --check . && eslint .",
"format": "prettier --plugin-search-dir . --write ."
```

There's also a [Prettier plugin for PHP](https://github.com/prettier/plugin-php), so it could definitely be cool to test it.

Also, I personally usually setup a `.editorconfig` file, which enforces some stuff across all files. See [this repo](https://github.com/jakobbouchard/umami-api-client) or [this repo](https://github.com/jakobbouchard/tomate) for an example. It can (and should!) be extended in eslint with `'plugin:editorconfig/noconflict'`, to prevent it from interfering with prettier too much (though prettier can read its settings, as you'll see in my repo).

Using EditorConfig would also help for other files that can't be processed by Prettier. At least on the line endings and indentation fronts.

**Comment by AlecRust** [comment]
100% agree re: Prettier. Feels like a following PR to this one though, especially if we include formatting of files.

> Also, I personally usually setup a .editorconfig file

We [have this already](https://github.com/hestiacp/hestiacp/blob/main/.editorconfig) as of recently, feel free to adjust these rules.

> It can (and should!) be extended in eslint

Wasn't aware of this thanks, will look in to it.

**Comment by imjuniper** [comment]
I honestly didn't look for the ediotrconfig, happy to see it's there!
And yeah, if you don't extend it in eslint, eslint will probably conflict with it

**Comment by jaapmarcus** [comment]
**How to release?**

1. Release via HestiaCP / "Us" 
There are 2 methods on how we build 
- Quick method .. On apt.hestiacp.com run https://github.com/hestiacp/hestiacp/blob/main/src/hst_autocompile.sh
- And have a coffee break first method https://github.com/hestiacp/hestia-build-drone

The last method we can simply extend with the 1 or 2 steps to build  css / javascript files
We can also add a "promote" function to drone.ylam that build only the package 

2. Run v-update-sys-hestia-git fork branch 
3. Run https://github.com/hestiacp/hestiacp/blob/main/src/hst_autocompile.sh

I have no idea how to solve it only adding depency for npm I assume?

**Comment by jaapmarcus** [comment]
> Where to lint?
>I've added a basic Drone job for ESLint in this PR, but Drone is slow/one build at a time. Front end linting could instead run with GitHub Actions ([example](https://github.com/actions/starter-workflows/blob/main/code-scanning/eslint.yml)) which would be faster and allow features like commenting on specific lines etc.

I am fine with Linting to Github actions we should also move as well Shell check (And if we improve our php testing) as well to git hub actions

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
