### PR TITLE
issue4401

### PR DESCRIPTION
**Pull request by jim-perkins**
[Bug] If outgoing mail servers checks for spam and uses BAYES then hestia marks all incoming email as spam even if spamassassin is disabled #4401

### CODE REVIEW

**Comment by divinity76** [comment]
Your approach is still wrong and would result in *nothing* being marked as spam, because you use $ to check that it "only" contains "Yes", which is never the case as it also adds some info about WHY it was marked yes or no.

Try
```
if $h_X-Spam-Status: begins "Yes"
```
or
```
if $h_X-Spam-Status: matches "^Yes"
```

**Review by divinity76 — CHANGES_REQUESTED** [review]
Nice catch 👍 

Your approach is still wrong and would result in *nothing* being marked as spam, because you use $ to check that it "only" contains "Yes", which is never the case because it also adds some info about WHY it was marked yes or no, for example
```
X-Spam-Status: Yes, hits=6.2 required=5.0 tests=REVERSE_AGING,VIAGRA
autolearn=no version=2.64-servername_config_v2
```

Instead Try
```
if $h_X-Spam-Status: begins "Yes"
```
or
```
if $h_X-Spam-Status: matches "^Yes"
```

**Comment by jim-perkins** [comment]
I dont run that outgoing mail server which put the Spam status in the header anymore so I cant test any requested changes, nor am I still affected by this bug.  

Rest assured the changes I noted still marked spam as spam on the mail server within hestia and the complete line was 'X-Spam-Status: Yes'.  I imagine there are many ways to setup spamassassin.  YMMV

More importantly any changes along this line does not fix the issue where no subject should be rewritten as SPAM if spamassassin is disabled.

I leave it up to the devs to modify my initial input or come up with whatever solution they deem effective.  Thanks for your input

**Review by divinity76 — APPROVED** [review]

**Comment by divinity76** [comment]
should be fixed now, thanks for investigating 👍

**Pull request merged**
