### PR TITLE
Update 10-master.conf

### PR DESCRIPTION
**Pull request by Yankie**
Fixed error:
auth: Error: passwd-file({USER}@{HOST},{IP},<sid>): open(somepath/passwd) failed: Permission denied (euid=97(dovecot) egid=97(dovecot) missing +r perm: somepath/passwd, we're not in group 12(mail), dir owned by 93:12 mode=0771)

see https://linuxdata.ru/questions/q164.html

I believe that all install scripts should be changed also...

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Installers should be fine as 10-master.conf will be used to overwrite default config files anyway...

 if we need to update something it would be the existing installs.

**Comment by Yankie** [comment]
Yeah, so did i last evening diggin' on how to add roundcube to working install of hestiacp, and get LE certs working on mail domains 
(if you skip dovecot install - mail domains will not get LE certs - due to mail domain LE configs not read - so LE host get 404 on domain check)

**Comment by Yankie** [comment]
> Installers should be fine as 10-master.conf will be used to overwrite default config files anyway...

i remember there was some `sed 's/// 10-master.conf' in install scripts...

**Comment by Yankie** [comment]
> > Installers should be fine as 10-master.conf will be used to overwrite default config files anyway...
> 
> i remember there was some `sed 's/// 10-master.conf' in install scripts...

https://github.com/hestiacp/hestiacp/blob/b024c68eb98072585892297870705c5b3ee20155/install/hst-install-ubuntu.sh#L1937

https://github.com/hestiacp/hestiacp/blob/b024c68eb98072585892297870705c5b3ee20155/install/hst-install-debian.sh#L1909

and maybe should be added here:

https://github.com/hestiacp/hestiacp/blob/b024c68eb98072585892297870705c5b3ee20155/install/common/dovecot/dovecot.conf#L9

**Comment by jaapmarcus** [comment]
If Dovecot and Mysql are selected we will also install Roundcube. 

v-add-sys-roundcube will install it on webmail.domain.com (Including SSL when enabled)

**Comment by jaapmarcus** [comment]
> > > Installers should be fine as 10-master.conf will be used to overwrite default config files anyway...
> > 
> > 
> > i remember there was some `sed 's/// 10-master.conf' in install scripts...
> 
> https://github.com/hestiacp/hestiacp/blob/b024c68eb98072585892297870705c5b3ee20155/install/hst-install-ubuntu.sh#L1937
> 
> https://github.com/hestiacp/hestiacp/blob/b024c68eb98072585892297870705c5b3ee20155/install/hst-install-debian.sh#L1909

Please include them in this PR  so it will not forgotten :)

**Comment by Yankie** [comment]
> > > > Installers should be fine as 10-master.conf will be used to overwrite default config files anyway...
> > > 
> > > 
> > > i remember there was some `sed 's/// 10-master.conf' in install scripts...
> > 
> > 
> > https://github.com/hestiacp/hestiacp/blob/b024c68eb98072585892297870705c5b3ee20155/install/hst-install-ubuntu.sh#L1937
> > 
> > https://github.com/hestiacp/hestiacp/blob/b024c68eb98072585892297870705c5b3ee20155/install/hst-install-debian.sh#L1909
> 
> Please include them in this PR so it will not forgotten :)

Just checked on code - its in Install Sieve part, and that means that dovecot is installed already. But i'm not sure about should line `extra_groups = mail`  be added to:

https://github.com/Yankie/hestiacp/blob/158b8343e46ff20db0249327503d52889d208549/install/upgrade/manual/install_sieve.sh#L50

Is it ok if it doubles?

**Comment by Yankie** [comment]
BTW
Those sed-lines in install scripts are under Install Sieve part will add copy of existent section...
I mean if you doing standard install with Dovecot + Sieve there will be 2 same sections of `unix_listener auth-master`...
Is it ok?

**Comment by jaapmarcus** [comment]
> BTW
> Those sed-lines in install scripts are under Install Sieve part will add copy of existent section...
> I mean if you doing standard install with Dovecot + Sieve there will be 2 same sections of `unix_listener auth-master`...
> Is it ok?

We should delete them. As it does exactly what your PR does.

**Comment by Yankie** [comment]
So merge, plz :)

**Comment by Yankie** [comment]
> > BTW
> > Those sed-lines in install scripts are under Install Sieve part will add copy of existent section...
> > I mean if you doing standard install with Dovecot + Sieve there will be 2 same sections of `unix_listener auth-master`...
> > Is it ok?
> 
> We should delete them. As it does exactly what your PR does.

I've checked again - they are different, so should be left as is.

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
