### PR TITLE
Simplify Password Generation in Installation Scripts

### PR DESCRIPTION
**Pull request by vestacp-user**
Minor and low priority housekeeping code suggestion
Less code, simpler code, easier to maintain, more people can understand
Rely on standard utilities that are subject to their own security audits

### CODE REVIEW

**Comment by ghost** [comment]
Your approach does have a problem. There's no hard limit on how much data will be read from urandom. One solution I can think of would be to read a fixed amount of data from urandom with the command of your choice and then run it through base64 encoding. This will always consume a fixed amount of bytes so it doesn't have this problem. If the character set of base64 isn't to your liking you can run it through a tr pass to convert them to something else. It's not like we need to recover the data stream used for this so it would be fine.

**Comment by vestacp-user** [comment]
I am not sure I follow.  The pipe has a max buffer size, thus it's "hard limit" as you say.  It will work on packets of max buffer size.  Additionally, if /dev/urandom runs of of entropy, thus slows down the transfer of random data, the whole pipe chain processing will just slow down also.

See `man pipe` and `man urandom` for more details. 

I don't see any condition where this will fail.  If you want to validate, try the following commands on the various relevant Distros and Releases:
`cat /dev/urandom | cat > /dev/null`
`cat /dev/urandom | tr -dc [:alnum:] | cat > /dev/null`
`cat /dev/urandom | tr -dc [:alnum:] | head | cat > /dev/null`

You can send to your terminal instead of /dev/null if you want to see the data.

Or propose a counter example which demonstrates a failure.  Aditionally, we are just reading for a 16 character password.  Keep in mind that I could scrub a whole drive with TBs of /dev/urandom.

If there is a failure case, then openssl would be the next random password source I could propose.

**Comment by ghost** [comment]
It won't fail. I was referring to how you read from it. Head limits the total output to 16 bytes but tr will consume potentially many more depending on how soon it finds bytes that match its filter criteria. If you instead encode the bytes you won't need to read as many.

**Comment by vestacp-user** [comment]
Doesn't matter, pipe will only pass on what it receives directly.  Thus head will wait for exactly 16 characters from tr.  Please provide an example where we received less characters than the 16 requested from head.

Try the following to see you will receive 16 character 'A':
`cat /dev/urandom | tr -dc A | head -c16`

**Comment by ghost** [comment]
Of course it does. That wasn't my point. Your method requires you to read, on average, approximately 4 times as many bytes since it only selects 62 of the possible 256 values. I guess it's ultimately irrelevant though. Is the read cost even that high? Nevermind.

**Comment by vestacp-user** [comment]
The original password generation code is a loop in Bash programming language.  Cat, tr, pipe, head are compiled C/C++.  Completely orders of mangnitude faster than anything in Bash.

But speed is irrelevant here, it is for 16 characters which run a few times on installation.  For many reasons, you want to offload simple task to standardized utilities when you can and simplify the HestiaCP code to reduce the long term maintenance efforts and increase transparency and acceptance.  They are optimized, maintained, reviewed, audited, documented and tested by millions.

Lots of documentation backing what I just proposed.  No documentation for the existing gen_pass function.

**Comment by kpapad904** [comment]
I use dd to limit the data from urandom and output passwords of 10-12 chars (which is more than enough) e.g.:

dd if=/dev/urandom count=1 bs=96 2> /dev/null | tr -dc 'a-zA-Z0-9' | cut -c-12

**Comment by kpapad904** [comment]
@vestacp-user I fully support your initiative to improve HestiaCP's password generation and I would like to eventually see similar improvements to the format used to store passwords on disk.

HestiaCP is currently using the weak MD5 password hashing algo. A few weeks ago I suggested replacing MD5 with BCRYPT, which since years is the default password hashing function of all software used by HestiaCP (note: PHP since 5.5.0, Dovecot and Apache), see https://github.com/hestiacp/hestiacp/issues/895

**Comment by vestacp-user** [comment]
Thank you for your input, but with all due respect, I would argue that it complicates the code with no jutified benefit.  Is there a measureable and relevant difference in performance or failure case that justifies the more compicated syntax?  Widespread usage of urandom, cat, tr, head ensures their safety and efficiency.  Simpler code is easier to audit.

**Comment by vestacp-user** [comment]
@kpapad904 for the storage of passwords, I am not there yet, but I will take a look once I dig there.

**Comment by kpapad904** [comment]
Another option could be the pwgen tool (by the well known Linux dev Theodore Ts'o), which is available for all supported versions of Debian, Ubuntu (and CentOS/RHEL).

https://packages.debian.org/source/sid/pwgen

**Comment by kpapad904** [comment]
@vestacp-user FWIW your simple implementation looks fine to me. And afaik consuming more data than absolutely necessary from /dev/urandom would create no problems to any modern Linux system (limiting it with dd was still useful 10+ years ago).

**Comment by jaapmarcus** [comment]
/dev/urandom is not blocking at the cost of being less random.  See https://en.wikipedia.org/wiki//dev/random. I think we are save to use it

We also need to replace https://github.com/hestiacp/hestiacp/blob/32062dc579b620f7f2d1061ba6d533445a494402/func/main.sh#L165-L181

**Comment by vestacp-user** [comment]
@kpapad904 pwgen could be interesting, I am assuming you would want to use it for more meaningful and easy to remember passwords.  However, it would be up to the project to decide since it would be more of a change than just simplifying the generation a 16 character password.  If requested, I can implement it.

If you want to go beyond urandom for the entropy of random key generation, I would use ssh-keygen with the ed25519 algo. Although ssh-keygen is certainly overkill, it has the advantage that the procedure can be used elsewhere in the project, and it would keep the code simple and it defers the audit to ssh which is widely used and audited.   I can also do that if the project wants.

**Comment by vestacp-user** [comment]
@jaapmarcus hestiacp/func/main.sh is deeper within Hestia and I am not yet at a point where I can test it enough to be comfortable to submit a pull for that change.

**Comment by kpapad904** [comment]
@jaapmarcus Wrt /dev/urandom I had in mind the points outlined here:

https://www.2uo.de/myths-about-urandom/

which basically says that in recent Linux kernels we can use /dev/urandom without any disadvantages. But I'm not an expert in the subject.

**Comment by vestacp-user** [comment]
@jaapmarcus hestiacp/func/main.sh, but I can submit the change if others that know it well enough want to test and confirm it.

**Comment by jaapmarcus** [comment]
It was also more reminder that we need to replace it add not forget about it. 

Any gen_pass is currently called maximum twice. Once when --password flag is missing and the second time to generate a password dbconfig user of Mysql. As long the password is random enough and not blocking the installation process it really doesn't matter. When those requirements it should be fine. What we use...

**Comment by vestacp-user** [comment]
Just for reference on this thread:

`man urandom`:
> When the entropy pool is empty, reads from **/dev/random** will block until additional environmental noise is gathered.

However: 

> The **/dev/random** interface is considered a legacy interface, and **/dev/urandom** is preferred  and  sufficient  in all use cases

**Comment by vestacp-user** [comment]
I just added the other places I could find.  A view minor questions from my tests:

1) test_actions.sh returned the following error, I assume it is normal
DNS: Duplicate record check                                [FAILED]

2) I was not able to test test.bats.  It gave me errors even after installing bats because I don't know what it does and how to do it.

**Comment by jaapmarcus** [comment]
test_actions is the old test script to preform automated testing

test.bats is used for automated testing in new releases.

**Review by ScIT-Raphael — APPROVED** [review]

**Pull request merged**
