### PR TITLE
[Feature] Add v-dump-site

### PR DESCRIPTION
**Pull request by hudokkow**
Please do not merge before we discuss.

Similar functionality to https://github.com/hestiacp/hestiacp/pull/3644 but for the site files.

A couple of questions regarding your preferences:
- archive type: zip, tar, tar.gz? Which one should I use? Zip is more common and I'm guessing a lot of folks don't use *nix every day.
- By default, do you want to archive everything under `/home/$user/web/$domain/` or is `/home/$user/web/$domain/public_html/` ok? I kinda like the latter.

Please decide. I'll accommodate the changes, if any, and force push to update this PR.

Have a great one!

### CODE REVIEW

**Comment by jaapmarcus** [comment]
I wonder what the advantage over creating a backup or just use sftp to download It. 

v-dump-database as phpmyadmin sucks at exporting larger databases.. And a lot of times I experinced issues with  it as it was slow as f***. 

I would prefer see a function to clone a website to a new domain in Hestia as for example staging ...

**Comment by hudokkow** [comment]
Ease of use and quick access. Together with a database dump you have pretty much everything you need to move from staging to prod server, something I do quite often. Also why I would prefer to only dump `public_html`.  Clients can give their staff the files and off they go.

BTW, clone is [coming](https://github.com/hudokkow/hestiacp/commits/clone_website).

Just need a few (lot?) more days to test and possibly rewrite code to reuse already present code and functions in Hestia's repo. Or leave the rewriting for later since I'm only starting to get my feet wet in Hestia's codebase. :-)

**Comment by jaapmarcus** [comment]
> Ease of use and quick access. Together with a database dump you have pretty much everything you need to move from staging to prod server, something I do quite often. Also why I would prefer to only dump `public_html`. Clients can give their staff the files and off they go.
> 
> BTW, clone is [coming](https://github.com/hudokkow/hestiacp/commits/clone_website).
> 
> Just need a few (lot?) more days to test and possibly rewrite code to reuse already present code and functions in Hestia's repo. Or leave the rewriting for later since I'm only starting to get my feet wet in Hestia's codebase. :-)

Depending on the software used they might also use folder in /home/user/web/domain/dir

**Comment by hudokkow** [comment]
That's decided. `/home/$user/web/$domain/` it is.

**Comment by johnnyq** [comment]
@hudokkow neat a feature I didn't know I needed until now. It would be awesome to also create another function to download mail domain and individual mailboxes. For Quick Archival Purposes

**Comment by hudokkow** [comment]
Out of scope for me. At least for now. I'm focusing on stuff I need every day.

**Comment by johnnyq** [comment]
Gotchya that makes sense

**Comment by jaapmarcus** [comment]
I assume it is ready for review?

**Comment by hudokkow** [comment]
Yes, thank you.

**Review by ghost — APPROVED** [review]

**Pull request merged**
