### PR TITLE
Update legacy /var/run directory to /run

### PR DESCRIPTION
**Pull request by istiak101**
Updated legacy rundir to /run.

`Dec 14 20:15:03 host.example.com systemd-tmpfiles[499]: /usr/lib/tmpfiles.d/dovecot.conf:1: Line references path below legacy directory /var/run/, updating /var/run/dovecot → /run/dovecot; please update the tmpfiles.d/ drop-in file accordingly.`

Similar logs will pop-up in journalctl with legacy /var/run.

Refs:
https://access.redhat.com/solutions/4154291
https://bugs.launchpad.net/ubuntu/+source/dbus/+bug/1854314

### CODE REVIEW

**Comment by jaapmarcus** [comment]
It makes sense to make the changes do we want to update existing configs?

**Comment by istiak101** [comment]
Yes, we will need to. Otherwise systemd will complain.

Context: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html

Linux FHS was updated /var/run to /run in 2015. Older LTS system with systemd won't complain but upgrading to newer distro with systemd will complain about this.

**Comment by jaapmarcus** [comment]
In that case we should include it in this PR.

As we don't support 16.04 any more this should be no issue

**Comment by istiak101** [comment]
I will have to spin up some 18, 20 Ubuntu and Debian 10 and see what their FHS is and do some testing. I will push updates in this PR.

**Comment by jaapmarcus** [comment]
Debian had no issues (10 and 11 tested) 

Will do a quick test for Ubuntu 18.04

**Review by jaapmarcus — APPROVED** [review]

**Comment by jaapmarcus** [comment]
Tested 18.04 as well also included the upgrade script that should convert existing config and so on.

**Comment by istiak101** [comment]
Thanks for taking care of this. Couldn't manage time due to personal issues. Hopefully will pick up RHEL branch again soon.

**Comment by youradds** [comment]
Its worth noting that some programs like **Monit** will need updating. I couldn't work out why mysql kept restarting - but it looks like its because it was looking for the wrong files since the update:

```
check process mysqld with pidfile /var/run/mysqld/mysqld.pid

if failed unixsocket /var/run/mysqld/mysqld.sock protocol mysql for 3 times within 4 cycles then restart
```

Hopefully that fixed it (now I just need to update all my other servers... oops)

**Pull request merged**
