### PR TITLE
Feature/b2 backup support

### PR DESCRIPTION
**Pull request by ScIT-Raphael**
Rewrite of https://github.com/hestiacp/hestiacp/pull/1496, to add it just run: `v-add-backup-host b2 bucketName keyName applicationKey`

### CODE REVIEW

**Comment by jaapmarcus** [comment]
We should add an Web GUI.

**Comment by jaapmarcus** [comment]
Add WebUI support
Add check at v-add-backup-host to prevent wrong data entered and only see when backup has been created 
Added information v-list-backup-host

**Review by jaapmarcus — APPROVED** [review]

**Comment by ScIT-Raphael** [comment]
I'll do some small code format tomorrow and merge the pr.

**Comment by jaapmarcus** [comment]
Replaced  the link to remote backup "tab" with an checkbox it will make it not necessary to empty "Bucket" or "host"
Screenshot 2021-01-12 at 09 38 01

**Pull request merged**
