### PR TITLE
Prestashop Nginx Templates

### PR DESCRIPTION
**Pull request by madito**
Add prestashop template for nginx.

Ref https://devdocs.prestashop.com/1.7/basics/installation/nginx/

### CODE REVIEW

**Comment by Lupul** [comment]
Thanks for taking the time to improve nginx templates.

A couple of notes:
- inconsistent identation in some places
- is this block here needed `tryfiles` vs `if !-e $request_filename`, at first impression looks redundant ?
https://github.com/hestiacp/hestiacp/pull/1196/files#diff-2a735c507f54a609a65e1bd5fd4e99c7R137-R140
- how is the random admin folder handled?
- haven't checked but isn't gzip compression already enabled by default? (https://github.com/hestiacp/hestiacp/blob/0e40dcb182dd3a881d922330ee9ad41fbbd80057/install/deb/nginx/nginx.conf#L72-L82)

Are you using this tpl currently in production?

**Comment by ioannidesalex** [comment]
Making a few optimizations and compatibility fixes.

**Comment by ioannidesalex** [comment]
Even though I am not using Prestashop, I believe there won't be any problems with my changes. I believe it's an improved version over the original and better adapted for HestiaCP.

**Comment by madito** [comment]
> Thanks for taking the time to improve nginx templates.
> 
> A couple of notes:
> 
> * inconsistent identation in some places
> * is this block here needed `tryfiles` vs `if !-e $request_filename`, at first impression looks redundant ?
>   https://github.com/hestiacp/hestiacp/pull/1196/files#diff-2a735c507f54a609a65e1bd5fd4e99c7R137-R140
> * how is the random admin folder handled?
> * haven't checked but isn't gzip compression already enabled by default? (https://github.com/hestiacp/hestiacp/blob/0e40dcb182dd3a881d922330ee9ad41fbbd80057/install/deb/nginx/nginx.conf#L72-L82
>   )
> 
> Are you using this tpl currently in production?

Thank you very much for the suggestions and changes.

Last changes working in production

The random admin folder, prestashop in its documentation recommends blocking it, but in my normal use it is necessary to be able to access. That is why it is not in the template.

**Comment by Lupul** [comment]
`try_files` should have been kept as it is the preferred way to handle missing files and pretty urls in general
ref: https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#check-if-file-exists

**Comment by madito** [comment]
Update code for tryfiles

**Comment by jaapmarcus** [comment]
Maybe it is me but I am getting only "error" 404 when visiting the website after the template and Prestashop template.

**Comment by madito** [comment]
I use the template on two production sites and work perfect! What version are you use??

**Comment by jaapmarcus** [comment]
Just checked again the template seems to be fine. It only refuses to go over https://

**Pull request merged**
