### PR TITLE
add wildcard email account backup exclusion

### PR DESCRIPTION
**Pull request by asessa**

### CODE REVIEW

**Comment by asessa** [comment]
Ref. hestiacp/hestiacp#1788

**Comment by Lupul** [comment]
Please also check if the match is not too greedy. Eg exception for `account@domain.com` does not match also `account@domain.com.sg` and similar

**Comment by asessa** [comment]
the first match is unchanged (line 392) to domain (domain.com), then account. So wildcard exception on account will never match other domains

**Review by ScIT-Raphael — APPROVED** [review]

**Comment by Lupul** [comment]
Unfortunately wasn't available for the review request but I see the code hasn't changed in the mean time. The exclusion check code is still greedy and can potentially exclude more accounts than intended.

Some quick examples:

```
MAIL='domain.com:office:contact,domain.com.tld:office2:contact2:office,dev.domain.com:office3:contact3:office*'
echo "$MAIL" | tr ',' '\n' | grep 'domain.com:' | tr ':' '\n' | grep -E "^office|\*"
```
> office
> office3
> office*


```
echo "$MAIL" | tr ',' '\n' | grep 'domain.com:' | tr ':' '\n' | grep -E "^unknown|\*"
```
> office*

**Comment by jaapmarcus** [comment]
Just ran some tests on v-backup-user and the "patch" applied

domain.com
northdomain.com
south.domain.com
All with 3 email accounts: info, office, officex where the x = number 1 to 3 for each domain a unique one...

with: domain.xyz:*

2021-05-24 11:54:50 domain.xyz
2021-05-24 11:54:50 excluding mail account info
2021-05-24 11:54:50 excluding mail account office
2021-05-24 11:54:50 excluding mail account office1
2021-05-24 11:54:50 northdomain.xyz
2021-05-24 11:54:50 south.domain.xyz

With domain.xyz:offic*
2021-05-24 11:58:02 domain.xyz
2021-05-24 11:58:02 excluding mail account info
2021-05-24 11:58:02 excluding mail account office
2021-05-24 11:58:02 excluding mail account office1
2021-05-24 11:58:02 northdomain.xyz
2021-05-24 11:58:02 south.domain.xyz
2021-05-24 11:58:02 *** 3 domains ***

domain.xyz:info
-- MAIL --
2021-05-24 11:59:03 domain.xyz
2021-05-24 11:59:03 excluding mail account info
2021-05-24 11:59:03 northdomain.xyz
2021-05-24 11:59:03 south.domain.xyz
2021-05-24 11:59:03 *** 3 domains ***

So with the except it to greedy...

With the old method:
1. Didn't work
2. Din't work 
3. Works fine

**Comment by asessa** [comment]
consider you can't use the wildcard like offic*, but only * to exclude all accounts, in your case office* contains an * and is excluding all accounts, excluding with partials needs some rewrite of that part, where we check first for the full exclusion, then for the account/partial.

About the "greedy" grep problem, I think this problem is spread across other scripts too, like v-add-mail-account-alias, where you receive an error if you try to enter a new alias using a word which is already partially contained on other alias

**Pull request merged**
