### PR TITLE
Add optional support deleting spam for score > 10

### PR DESCRIPTION
**Pull request by jaapmarcus**
* Add optional support deleting spam for score > 10
* Add "*** SPAM ***" to the subject to emails considered SPAM (more than 5.0 points).
* Add "*** VIRUS ***" to the subject if you have detected a virus.

#2200

TODO Add Upgrade support with sed..

### CODE REVIEW

**Comment by kpapad904** [comment]
Your take on it looks nice and complete!

I don’t see a big problem with outright rejecting mails with super-high spam score (>10) as long as you do it properly with 55x during SMTP-time (and not drop it silently or send a DSN after accepting it) . In my experience, spam score >10 is either unquestionably spam or a misconfigured mailserver (e.g. SPF).

Instead of rewriting the Subject to `*** SPAM ***` (a change which can't be undone), another approach would be to use Dovecot system-wide Sieve filters to move `X-Spam-Status: Yes` mails to the Junk/Spam folder. The only downside of that approach would be that any users downloading their emails with POP3 instead of IMAP won’t be able to download any emails moved into the Junk/Spam folder.

**Comment by kpapad904** [comment]
This article is quite old (2015) but the section "Sending spam to the Junk folder" explains in detail how to move `X-Spam-Status: Yes` mails to the Junk/Spam folder:

https://workaround.org/ispmail/jessie/spamassassin

It also includes a warning that mails in Junk aren't downloaded by POP3 users:

> Big fat red blinking warning: this does not work for users fetching mail using the POP3 protocol. POP3 just reads the inbox but cannot access any other folders. So those users will inadvertently assume that emails got lost because they do not see the “Junk” folder. In fact I would not suggest offering POP3 at all but I can’t tell whether it’s still a commonly used protocol.

**Review by ScIT-Raphael — CHANGES_REQUESTED** [review]
Work on update script pending.

**Comment by jult** [comment]
Who is still using POP3? I mean, look at the stats of your server logs. And if they have the "leave messages on server" tagged, which most of them do, because they also want to use webmail, just force them to use IMAP instead.

**Pull request merged**
