### PR TITLE
[WIP] Attempt to fix SFTP jail for FTP accounts

### LINKED ISSUE #936: Discussion - Disable vsftpd by default for new installations?
While configuring my server I ended up doing research on major FTP clients. Most of the popular ones support SFTP already as they are multi-protocol clients. Most of what the FTP server is used for in Hestia is already doable over SFTP. The rest can be handled by HTTP or HTTPS for anonymous downloads. Given that the FTP server is largely redundant due to other parts doing most of what it does already, does it still make sense to enable an FTP server by default?

### PR DESCRIPTION
**Pull request by ghost**
This works by switching openssh to use a different chroot that is
root owned and only writeable by root to serve as the new chroot
root directory. The SFTP server is now told to chdir to the custom
home directory path so all sessions will start relative to this one
to ease issues with possible clients.

But that's not all. Something has to bind mount the user directory
as well and that is where the systemd mount and automount units come
in. They will bind mount the home directory into the chroot home
directory when anything attempts to access it and it will also unmount
the bind mount if it is idle after awhile.

(Closes #936)

### CODE REVIEW

**Comment by ghost** [comment]
Alternatively, you can write the entries to fstab but this modular approach is easier to maintain since you don't need hacks to maintain the fstab contents.

**Comment by ghost** [comment]
On second thought I think it may be better if I can find some scheme to mount this via PAM. That way the cleanup can be tied to the session exit.

**Comment by jaapmarcus** [comment]
Just checked it and after a few issues from my side it worked fine. 

To install the sftp jail run first to get it working

```
 v-delete-sys-sftp-jail 
 v-add-sys-sftp-jail 
```

**Comment by ghost** [comment]
Indeed it does. I'm currently working on an improvement since I think pam_mount is more suitable due to not having to generate some systemd files every time. I can rely on some static configuration for it. It's less of a burden for maintenance too.

**Comment by ghost** [comment]
It should be finished. Ready for review. @jaapmarcus You should be able to apply the work by just removing the systemd mount files manually and re-running the scripts. Incidently I found I can't actually use pam_mount because it conflicts with what I'm trying to do. It insists on changing the permissions of the created directories. I ended up writing my own short script to execute with pam_exec that solves the problem quite well.

**Comment by ghost** [comment]
Incidentally we may want to revise the FTP configuration to use the new SFTP jail system since they're compatible. I know we intend to disable it but it wouldn't hurt to strength it for those that still want to use it.

**Comment by jaapmarcus** [comment]
@braewoods  I agree if we can strengthen it it is never a bad idea. As many users still prefer FTP over SFTP...

For the changes I will check it later on...

If persons want to test please use

`v-update-sys-hestia-git braewoods main yes`

**Comment by ghost** [comment]
@jaapmarcus Ok. I found out how to jail vsftpd like it is for openssh. It isn't hard at all. Only thing I can't do much about is the starting directory.

**Review by ScIT-Raphael — APPROVED** [review]

**Comment by kpapad904** [comment]
While reworking the sftp jail, could you also get rid of the sftp_dummy99 user, as suggested in https://github.com/hestiacp/hestiacp/issues/700#issuecomment-584819608

**Comment by kpapad904** [comment]
I have just manually tested your changes in a Debian10 LXD/LXC container (note: I was a bit anxious about potential issues due to the use of mount --bind inside the container) running HestiaCP 1.2.1-beta.

I just logged into the system with sftp. Please let me know if there is anything you want me to test.

**Comment by jaapmarcus** [comment]
Create a Additional FTP user from the "Web" when editing a domain. 

And login with SFTP. We are considering dropping FTP on default

**Comment by ghost** [comment]
@kpapad904 I'll take a look.

**Comment by kpapad904** [comment]
Here is a pastebin with the testing sofar:
https://pastebin.com/z3nTQueY

**Comment by ghost** [comment]
After some analysis I think we would need to use sshd's include feature to put the jail in a separate file because of how openssh's matching logic works. We only want to enable it for users without a regular login shell which precludes the hard-coded approaches using fixed matches for admin user and hestia-users group. Though the problem with this is how to switch people to it. It presents an upgrade challenge.

**Comment by kpapad904** [comment]
According to jaapmarcus directions, I created additional FTP user from the WebGUI and tried to login with SFTP. The main user connected fine with sftp (as before), however the additional ftp user couldn't connect: 

Here is a pastebin with the 2nd round of testing:
https://pastebin.com/0F3JnntS

**Comment by ghost** [comment]
We cannot drop the dummy user hack for now. It's just not possible to avoid editting sshd_config because split configuration isn't even possible until *very* recent releases of openssh.

**Comment by ghost** [comment]
Please wait to try to use this branch a bit longer. I'm trying to find a way to make it work with vsftpd as well. It's not really responding to PAM modules at all so I think I will have to use another approach.

**Comment by ghost** [comment]
Ok. It should be ready for further testing.

**Comment by jaapmarcus** [comment]
Sftp was working fine but couldn't login with ftp.

**Comment by ghost** [comment]
It works from an upgrade from a clean LXC Ubuntu 20.04 container at version 1.2.0 though I noticed I had to perform the upgrade twice for the upgrade script to apply. What was your testing environment? Maybe there's some environment specific issue I need to look at.

**Comment by ghost** [comment]
Tested it with Debian 10. It works there. I wonder why it wasn't working for you.

**Comment by jaapmarcus** [comment]
> Tested it with Debian 10. It works there. I wonder why it wasn't working for you.

Did it on a clean install it worked fine. Think I / the system  messed up during testing older versions. 

One thing I noticed 
root@dev:~# v-delete-user-sftp-jail [user]

Does remove the /srv/ftp/user folder but not the sftp /srv/jail/user folder also in /etc/systemd/system the srv-jail-user-home.mount still exists.

Executing the command in did the same with delete-web-domain-ftp [user] domain [user]_test and it worked file

Als in the last case the folder in /srv/jail/{user}/ still remains

**Comment by ghost** [comment]
Intentional because removal may fail due unmounting failing but I can see about removing it when the chroot jail is deleted. I changed to lazy unmount so it might still work.

**Comment by ghost** [comment]
It should now delete the directory along with the mountpoint.

**Comment by ghost** [comment]
@jaapmarcus I didn't see you were also referring to sftp jail command. That's intentional because it has to remain in tact for FTP jails to continue to function. The command `v-delete-user-sftp-jail` just disables using it for SFTP. I thought this was acceptable since FTP was already jailing users regardless in their home directories.

**Pull request closed without merging**
