### PR TITLE
feat: update os check script to support Ubuntu 24.04

### PR DESCRIPTION
**Pull request by dadangnh**

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Comment by jaapmarcus** [comment]
Looks fine for me!

**Comment by mehdiMj-ir** [comment]
Even though 24.04 support mentioned on your Readme page, when I try to install your application it didn't work/support Ubuntu 24.04
Screenshot_20241220_004654

**Comment by divinity76** [comment]
@mehdiMj-ir it has not made it's way to a stable release *yet*. See https://forum.hestiacp.com/t/alpha-hestia-1-9-help-wanted/15193 for the beta installer, where 24.04 is supported.

**Comment by mehdiMj-ir** [comment]
I just installed https://beta-apt.hestiacp.com/hst-install-ubuntu.sh and review your app, It works fine, hope you best success on you app.
If you guys could add centeral search option like WHM/cPanel it would be a huge game changer.

**Pull request merged**
