### PR TITLE
fix/use v-list-sys-sshd-port to check custom ssh port#3921

### PR DESCRIPTION
**Pull request by sahsanu**
Modify `v-add-firewall-chain` and `v-update-firewall` to use `v-list-sys-sshd-port` instead of `grep sshd_config` file to check what is the used ssh port.

### CODE REVIEW

**Review by jaapmarcus — CHANGES_REQUESTED** [review]
In "cases" where the user has multiple ports defined It will return a list like
```
port1
port2
```

```
for port in $($BIN/v-list-sshd-port plain); do
  if [ -n $ssh_port ]; do
 ssh_port="$ssh_port,$port" 
else
 ssh_port=$port
fi
done
```
We should accommodate so it will add both it to the list.

Probably applying a regex will not hurt imo

Not tested  yet...

**Comment by sahsanu** [comment]
I thought about it but I wanted to leave it the same as the previous grep that only took into account the first port found.

With sed you can easily fix it so that it joins the lines it finds separated by commas.

`v-list-sys-sshd-port plain | sed ':a;N;$!ba;s/\n/,/g'`

Output sample using default port (not modifiying Port directive):

```
# v-list-sys-sshd-port plain | sed ':a;N;$!ba;s/\n/,/g'
22
```

Output sample using custom port 2222:

```
# v-list-sys-sshd-port plain | sed ':a;N;$!ba;s/\n/,/g'
2222
```
Output sample using custom ports 2222 and 3333:

```
# v-list-sys-sshd-port plain | sed ':a;N;$!ba;s/\n/,/g'
2222,3333
```
Output sample using custom ports 2222,3333 and 4444:

```
# v-list-sys-sshd-port plain | sed ':a;N;$!ba;s/\n/,/g'
2222,3333,4444
```

If you agree I could modify the commit to use above sed...

**Comment by jaapmarcus** [comment]
Go ahead :)

**Comment by sahsanu** [comment]
Done. I had to replace bash regex by extended grep in `v-update-firewall`   script to match one or multiple ports separated by commas.

And there is a couple of typos in commits title (ti is to and allos should be allow) :(

**Comment by sahsanu** [comment]
@jaapmarcus Please, don't merge this pull request, we need to perform at least two more changes in `v-update-firewall`.

**1.-** If you have already changed the ssh port,  this sed won't modify `rules.conf` dir.

`sed -i "s/PORT='22'/PORT=\'$sshport\'/" $rules`

And we should use something like this instead:

`sed -i -E "s/(PORT=')[0-9]+(,[0-9]+)*('.*COMMENT='SSH')/\1$sshport\3/" $rules`

**2.-** Also, I think `chains.conf` should be also updated inside this script with something like this (just after previous sed) or it won't add the right ssh ports to iptables rules for fail2ban-SSH:

`sed -i "/CHAIN='SSH'/c\CHAIN='SSH' PORT='$sshport' PROTOCOL='TCP'" "$HESTIA/data/firewall/chains.conf"`

I'll wait till your comments.

**Comment by jaapmarcus** [comment]
Changes look fine  will test them shortly

**Comment by sahsanu** [comment]
Last commit for v-update-firewall:

Removed `&& [[ "$sshport" -ne "22" ]] `in if because if port is 22, the port won't be changed in `rules.conf `and `chains.conf` files

Replaced `sed -i "s/PORT='22'...` to allow any port in `rules.conf` file

Added sed command to replace the right ssh ports in `chains.conf` file. If we don't do this, those ssh ports won't be added to `fail2ban-SSH` chain.

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
