### PR TITLE
Update syshealth.sh

### PR DESCRIPTION
**Pull request by Skamasle**
Prevent this error https://github.com/hestiacp/hestiacp/issues/4523

### CODE REVIEW

**Comment by divinity76** [comment]
are you sure this changes anything? seems like the 2 should do the exact same thing, just with a different coding style?

testing it locally,
```sh
#!/bin/bash

# Test Case 1: Files are different
echo "Test content 1" > /tmp/file1
echo "Test content 2" > /tmp/file2

# Variables to store comparison results
NGINX_BCONF_CHANGED_1="no"
NGINX_BCONF_CHANGED_2="no"

# First snippet (explicit exit status check)
cmp --silent "/tmp/file1" "/tmp/file2"
[ $? -ne 0 ] && NGINX_BCONF_CHANGED_1="yes"

# Second snippet (using || operator)
cmp --silent "/tmp/file1" "/tmp/file2" || NGINX_BCONF_CHANGED_2="yes"

# Output the results for Test Case 1
echo "Test Case 1 (Files are different):"
echo "Result of first snippet: NGINX_BCONF_CHANGED_1 = $NGINX_BCONF_CHANGED_1"
echo "Result of second snippet: NGINX_BCONF_CHANGED_2 = $NGINX_BCONF_CHANGED_2"

# Reset variables for the next test
NGINX_BCONF_CHANGED_1="no"
NGINX_BCONF_CHANGED_2="no"

# Test Case 2: Files are the same
echo "Test content 1" > /tmp/file3
echo "Test content 1" > /tmp/file4

# First snippet (explicit exit status check)
cmp --silent "/tmp/file3" "/tmp/file4"
[ $? -ne 0 ] && NGINX_BCONF_CHANGED_1="yes"

# Second snippet (using || operator)
cmp --silent "/tmp/file3" "/tmp/file4" || NGINX_BCONF_CHANGED_2="yes"

# Output the results for Test Case 2
echo "Test Case 2 (Files are the same):"
echo "Result of first snippet: NGINX_BCONF_CHANGED_1 = $NGINX_BCONF_CHANGED_1"
echo "Result of second snippet: NGINX_BCONF_CHANGED_2 = $NGINX_BCONF_CHANGED_2"

# Clean up temporary files
rm /tmp/file1 /tmp/file2 /tmp/file3 /tmp/file4
```
output
```
Test Case 1 (Files are different):
Result of first snippet: NGINX_BCONF_CHANGED_1 = yes
Result of second snippet: NGINX_BCONF_CHANGED_2 = yes
Test Case 2 (Files are the same):
Result of first snippet: NGINX_BCONF_CHANGED_1 = no
Result of second snippet: NGINX_BCONF_CHANGED_2 = no
```

**Comment by Skamasle** [comment]
Hi, yes do the same, but not return exist code 1, when some subprocess return code 1 dpkg
detect it and fail.

The point is DPKG
cmp --silent "/tmp/file3" "/tmp/file4" <<<<<<<< Retun 1 -- DPKG take it and fail
[ $? -ne 0 ] && NGINX_BCONF_CHANGED_1="yes"
# this fail either if you put a exit 0 here because dpkg detect any subprocess not entery script exit.
cmp --silent "/tmp/file1" "/tmp/file2" || NGINX_BCONF_CHANGED_2="yes" <<<<<<<< This not return 1 to dpkg so works in same way but dpkg not detect any subprocess failing here.

Check it

Apt-get remove hestia-nginx
Apt-get install hestia-nginx


Dpkg detect if any subprocess in any script return 1, this avoid that.

But may my test fail, so please try reinstall hestia-nginx with this change
and without it and see if fail or not

**Comment by jaapmarcus** [comment]
I wonder what the code does it creates a backup after update already overwritten the nginx file. 

If it was up to me we should remove the check and create a preinstall that backs up the current "nginx" config before the install of the new package

**Comment by divinity76** [comment]
> Hi, yes do the same, but not return exist code 1, when some subprocess return code 1 dpkg detect it and fail. 

oh dang you're right, they set different return codes, my bad.
```
$? = 1
$? = 0
Test Case 1 (Files are different):
Result of first snippet: NGINX_BCONF_CHANGED_1 = yes
Result of second snippet: NGINX_BCONF_CHANGED_2 = yes
$? = 0
$? = 0
Test Case 2 (Files are the same):
Result of first snippet: NGINX_BCONF_CHANGED_1 = no
Result of second snippet: NGINX_BCONF_CHANGED_2 = no
```

**Comment by divinity76** [comment]
... but the error code should be overwritten by that rm -f on the next line anyway 🤔

**Comment by Skamasle** [comment]
Hi

Yes,  but no, dpkg get all exit codes, so as say, script can end en exit
code 0, but dpkg search for all codes of all lines, if one line, so one
subprocess ends with 1 dpkg inform about it, either if you add exit 0 at
the end of script.

For this reason, error say : subprocess return code 1, dpkg just need care
about all process in all systems exists good.

I'm wondering if dpkg continues execution after the last exit 1 code.

**Comment by Skamasle** [comment]
> I wonder what the code does it creates a backup after update already overwritten the nginx file.
> 
> If it was up to me we should remove the check and create a preinstall that backs up the current "nginx" config before the install of the new package

But is it really necessary to backup nginx.conf? The hestia-nginx.deb package already comes with a valid and functional file, meaning the original file is already in the package.

**Comment by jaapmarcus** [comment]
> > I wonder what the code does it creates a backup after update already overwritten the nginx file.
> > If it was up to me we should remove the check and create a preinstall that backs up the current "nginx" config before the install of the new package
> 
> But is it really necessary to backup nginx.conf? The hestia-nginx.deb package already comes with a valid and functional file, meaning the original file is already in the package.

At least not after running the update that is why this it should be made before the update is made ..  That why it is not needed to create a backup make the changes with sed and  keep / remove the temp file

Will close the PR and replace it with:
https://github.com/hestiacp/hestiacp/issues/4523

**Pull request closed without merging**
