### PR TITLE
Fix TLSProtocol compatibility for old versions of ProFTPD

### PR DESCRIPTION
**Pull request by myrevery**
ProFTPD's [docs](http://www.proftpd.org/docs/contrib/mod_tls.html#TLSProtocol) needs correction...

### CODE REVIEW

**Comment by jaapmarcus** [comment]
We noticed by bug report:
https://forum.hestiacp.com/t/ftp-access-failed-after-hestia-control-panel-v1-7-8-to-v1-8-1-update/10127/18

**Comment by myrevery** [comment]
Apologies to affected users...

**Comment by myrevery** [comment]
After reviewing all changes from version v1.3.6 of ProFTPD, seems older than v1.3.7a interact incorrectly with OpenSSL TLS 1.3 API.

For systems (Debian 10, Ubuntu 20.04) using older versions of ProFTPD, the only option is disable TLS 1.3 support.

**Review by jaapmarcus — APPROVED** [review]

**Comment by jaapmarcus** [comment]
Changes look fine

**Pull request merged**
