### PR TITLE
Feature/template for drupal version 8 and up

### PR DESCRIPTION
**Pull request by Devoleksiy**

### CODE REVIEW

**Comment by jaapmarcus** [comment]
I don't see any changes with the default template for everything. Is there any specific reason why we need this templates?

Also it is only for Nginx + Apache2 setup. The default.tpl should be enough?

**Review by jaapmarcus — CHANGES_REQUESTED** [review]
See last comment

**Comment by Devoleksiy** [comment]
The standard location for the application root for the Drupal CMS is the "web" directory.
That is, docroot will be /home/admin/web/example.com/public_html/web

**Comment by jaapmarcus** [comment]
If you go:
Screenshot 2023-08-18 at 10 10 54

You can do the same thing...

**Pull request closed without merging**
