### PR TITLE
[WIP] Add support for CentOS

### PR DESCRIPTION
**Pull request by Lupul**
Work in progress

### CODE REVIEW

**Comment by susinths** [comment]
@EquisTango: awesome work!

**Comment by avcvv** [comment]
How many time it will take to complete?

**Comment by ScIT-Raphael** [comment]
@avcvv sorry for the delay, there is no planed release time, as @Lupul wrote, work in progress.

**Comment by schiwe** [comment]
Keep Up The Good Work!

**Comment by devius** [comment]
Good work guys, I am waiting for CentOS support

**Comment by Freebase394** [comment]
@EquisTango   
@ScIT-Raphael
How are you guys? 
how is the progress of this adaptation?

**Comment by ScIT-Raphael** [comment]
mostly merged, I'll close it for now. Also due to the fact that they stopped the centos development.

**Pull request closed without merging**
