### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Minor spelling corrections, add missing Debian 12 support note

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Comment by myrevery** [comment]
I noticed that this GitHub account with the username "krismkenn" was just created.

For the safety of this project, ask Kristan Kenny to responsibly disclose more information.

Given that member Kristan Kenney has been inactive for a very long time, does the management team verified his authenticity in any effective way?

**Comment by ScIT-Raphael** [comment]
yes, he's verrified.

**Comment by myrevery** [comment]
in what way?

**Comment by ScIT-Raphael** [comment]
Honestly, I don't think this is really relevant, but if you're "that" interrested in it: old discord, existing discord account and his old email address.

**Comment by myrevery** [comment]
One potential risk is that Kristan Kenney's domain "kristankenney.ca" expired in 2017 and was then re-registered in 2019.

**Comment by ScIT-Raphael** [comment]
once again: VERRIFIED!

you dont even know which address or discord account. Thanks @krismkenn for closing the thread.

**Pull request merged**
