### PR TITLE
Feature DNS TTL #494

### PR DESCRIPTION
**Pull request by jaapmarcus**
Was checking if it was possible to implement DNS sec. How ever found this issue also open and it was an "easy" fix

Preferred order:
1. User selected value for option (Via v-add-dns-record / v-change-dns-record)
2. Default Settings for Zone file

Due to backward compatibility the command for both add/change are the same as the old one how ever added TTL at the end

./v-add-dns-record  USER DOMAIN RECORD TYPE VALUE [PRIORITY] [ID] [RESTART] [TTL]

Currently don't know a easy fix for (Or creating a new bash file for it) to alter the order

TTL is in seconds same as the default settings

### CODE REVIEW

**Comment by ScIT-Raphael** [comment]
Hi @jaapmarcus 

Awesome work, I think we also would need to check the cluster part (v-add-remote-dns-record and so on). Would you like to add ttl also there?

Really love your contribution, thanks for helping us out! If you would like to get in contact with the team, please write me a mail to info@hestiacp.com.

**Comment by jaapmarcus** [comment]
That was the only issue that I had.. couldn't found how the syncing worked. 

```
    # Syncing record
    str=$(grep "ID='$id'" $USER_DATA/dns/$domain.conf | sed 's/"/\\"/g')
    cluster_cmd v-insert-dns-record $DNS_USER $domain "$str" 'no'
    check_result $? "$HOST connection failed (record sync)" $E_CONNECT
```
So far In can see it it will copy the line from domain.conf that's allready in the format it will work

Maybe setup a 2nd vm and try it out.. (can't try it out on the live server to afraid to *** something up)

**Comment by ScIT-Raphael** [comment]
Usualy, you need to setup a different hestia server and add a dnsonly user. It looks like only the "v-insert-*" conmmands will be triggered, for example: https://github.com/hestiacp/hestiacp/blob/master/bin/v-insert-dns-domain

So I think tls has just to be added there also.

**Comment by jaapmarcus** [comment]
Just tested it with a 2nd VM server (Running last stable version)

And without any changes (except adding the cluster to the main system) it works straight out the box. 

ID='20' RECORD='test' TYPE='A' PRIORITY='' VALUE='myip' SUSPENDED='no' TIME='13:29:31' DATE='2020-04-29' TTL='500'

And in the domain.db on the slave
test	500	IN	A my-ip

So I think there is no issue with it.

**Comment by jaapmarcus** [comment]
Added a check if ttl was present or not. Should prevent empty ttl in some zone files

**Comment by Lupul** [comment]
prev approach was ok it just needed to fallback on zone ttl value when ttl argument was missing

**Comment by Lupul** [comment]
I'm gonna merge as is, and we will continue the improvements on master.
Thanks for taking the time to improve Hestia.

**Comment by jaapmarcus** [comment]
one thanks :)

**Pull request merged**
