### PR TITLE
White label for file manager

### PR DESCRIPTION
**Pull request by MaxiZamorano**
Changing the app name from the white label options will now also change it in the file manager, so the browser tab will now display the corresponding name.

Currently the default value is File Manager - Hestia Control Panel

With this change it will also display the name that is configured in the white label options in the Application Name field:

Captura de pantalla 2024-12-17 131347

### CODE REVIEW

**Review by jaapmarcus — CHANGES_REQUESTED** [review]
This will reset when we update the file manager so it should also be changed when we update / reinstall / install that..

**Comment by MaxiZamorano** [comment]
> This will reset when we update the file manager so it should also be changed when we update / reinstall / install that..

That's true, I'll think of some solution to solve that.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/82a2a1b8cc8f2652934212f5d8cc31fad0c7adfe/bin/v-add-sys-filemanager#L102-L104


$APP_NAME should exists here

https://github.com/hestiacp/hestiacp/blob/82a2a1b8cc8f2652934212f5d8cc31fad0c7adfe/func/upgrade.sh#L689-L691

Same here

**Comment by MaxiZamorano** [comment]
> https://github.com/hestiacp/hestiacp/blob/82a2a1b8cc8f2652934212f5d8cc31fad0c7adfe/bin/v-add-sys-filemanager#L102-L104
> 
> $APP_NAME should exists here
> 
> https://github.com/hestiacp/hestiacp/blob/82a2a1b8cc8f2652934212f5d8cc31fad0c7adfe/func/upgrade.sh#L689-L691
> 
> Same here

Thanks, I made the changes to those files.

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
