### PR TITLE
Update SOA Minimum TTL

### PR DESCRIPTION
**Pull request by manuelserol**

### CODE REVIEW

**Comment by Lupul** [comment]
Any context for this change? increasing negative caching TTL to 1h doesn't seem to be something we want to do unless there is a very good reason

**Comment by manuelserol** [comment]
After testing the DNS Records with two DNS Tools both warned that it should be between 1 to 3 hours so I asked on discord what about this and Jaap suggested to do a pull request.

The result of my tests:

**Comment by FalzoMAD** [comment]
citing RFC2308:

> As with caching positive responses it is sensible for a resolver to limit for how long it will cache a negative response as the protocol supports caching for up to 68 years.  Such a limit should not be greater than that applied to positive answers and preferably be tunable.  **Values of one to three hours have been found to work well and would make sensible a default**. Values exceeding one day have been found to be problematic.
   
this most likely is the part referred to as 'recommendation' by the dns tools you looked at. in fact this seems to merely recommend a max value and especially states it should not be bigger than positive caching (TTL) values. which by the way often are recommended to be kept in the range of 300-900 and might even be preferred by caching nameservers over the SOA.minimum anyway.

I suggest to put in a feature request for making the SOA records adjustable instead of having them hardcoded to one or another value _at all_.

**Comment by jaapmarcus** [comment]
There is already a feature request for it (At least for the values to be changeable)
https://github.com/hestiacp/hestiacp/issues/1672

**Comment by ghost** [comment]
Closing, please track progress under https://github.com/hestiacp/hestiacp/issues/1672.

**Pull request closed without merging**
