### PR TITLE
Include Alpine.js in main bundle

### PR DESCRIPTION
**Pull request by AlecRust**
And upgrade it from 3.10.15 -> 3.12.0.

Also removes "defer" attribute from script elements now that the way we load Alpine no longer depends on this, for a simpler setup. Can think about moving all JS from the head to the bottom of the HTML later on.

### CODE REVIEW

**Comment by imjuniper** [comment]
I think we could leave them deferred, that way they're not a blocking resource. in fact, ideally they'd be async and deferred, but jQuery's not happy when that happens. i'm fine with this though

**Comment by imjuniper** [comment]
keeping them in the head and async+deferred would make sure the browser doesn't wait for it, then run it, then load the rest of the HTML/CSS. it would all load at the same time-ish

**Comment by AlecRust** [comment]
I think I actually had Alpine init issues when I moved it into the bundle, and all scripts were still deferred. Could tinker more with it though.

Moving all JS loading to bottom of HTML would also prevent blocking?

**Comment by imjuniper** [comment]
yeah, moving it to the bottom would make it not blocking, but the browser will only start downloading the script once it reaches the `script` tag, so after the page is fully loaded. if we put it in the head with `defer`, it will block for the download, but wait for execution. adding `async` would also make the download non-blocking. at least I think? that's what I remember from last time I checked/tested.

**Comment by AlecRust** [comment]
Fair enough. But adding `defer` attributes back as they were breaks Alpine initialisation. So this will need some more work if we want to keep that approach.

**Review by jaapmarcus — APPROVED** [review]

**Comment by AlecRust** [comment]
Closing for now, can take another stab that retains `defer` at some point. Not massively important.

**Pull request closed without merging**
