### PR TITLE
Refactor translations

### LINKED ISSUE #1606: [FEATURE] Make HESTIA panel's email templates customizable / translatable
**When you create a client or a domain...**

The emails from the panel are sent in english and the text can't be edited.

### LINKED ISSUE #2493: Add White label options to Hestia CP
### Describe the feature or change in detail

Add setting to dashboard where you can edit APP_NAME (now it is "Hestia Control Panel"), that is used as email from, in titles, email signature, etc.

I think that there could be also way to edit favicon and logo.

### Would you like to sponsor this feature to have it implemented?

Yes

https://app.bountysource.com/issues/118691101-add-white-label-options-to-hestia-cp

### LINKED ISSUE #3359: [Bug] nginx-error.log get spammed with Undefined variable
### Describe the bug

the nginx-error.log is spammed with:

`2023/03/18 06:50:03 [error] 337360#0: *27810 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $user_plain in /usr/local/hestia/web/templates/includes/js.php on line 30; PHP message: PHP Warning:  Undefined variable $user_plain in /usr/local/hestia/web/templates/includes/js.php on line 31; PHP message: PHP Warning:  Undefined variable $user_plain in /usr/local/hestia/web/templates/includes/js.php on line 32; PHP message: PHP Warning:  Undefined variable $error in /usr/local/hestia/web/templates/pages/login/login.php on line 11" while reading response header from upstream, client: xx.xx.xx.xx, server: _, request: "GET /login/ HTTP/1.1", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "xx.xx.xx:8083"
`
and there is 1 Line with a deprecated warning:

`2023/03/18 06:47:49 [error] 337360#0: *27755 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_redirect_custom in /usr/local/hestia/web/templates/pages/edit_web.php on line 150; PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 406; PHP message: PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/hestia/web/templates/pages/edit_web.php on line 406" while reading response header from upstream, client: xx.xx.xx.xx, server: _, request: "GET /edit/web/?domain=xxxx.at&token=64d1xxxxxxxxxxxx875a184ad HTTP/1.1", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "xx.xx.xx:8083", referrer: "https://xx.xx.xx:8083/list/web/"`

### Tell us how to replicate the bug

check nginx-error.log

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.7.0beta6

### Operating system

Ubuntu 22.04

### Log capture

```shell
2023/03/18 06:47:49 [error] 337360#0: *27755 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_redirect_custom in /usr/local/hestia/web/templates/pages/edit_web.php on line 150; PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 406; PHP message: PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/hestia/web/templates/pages/edit_web.php on line 406" while reading response header from upstream, client: xx.xx.xx.xx, server: _, request: "GET /edit/web/?domain=xxxxxx.at&token=64d1xxxxxxxxxxxxxxxxxa184ad HTTP/1.1", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "xx.xx.xx:8083", referrer: "https://xx.xx.xx/list/web/"
2023/03/18 06:48:03 [error] 337360#0: *27796 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $user_plain in /usr/local/hestia/web/templates/includes/js.php on line 30; PHP message: PHP Warning:  Undefined variable $user_plain in /usr/local/hestia/web/templates/includes/js.php on line 31; PHP message: PHP Warning:  Undefined variable $user_plain in /usr/local/hestia/web/templates/includes/js.php on line 32; PHP message: PHP Warning:  Undefined variable $error in /usr/local/hestia/web/templates/pages/login/login.php on line 11" while reading response header from upstream, client: xx.xx.xx.xx, server: _, request: "GET /login/ HTTP/1.1", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "xx.xx.xx:8083"
```

### PR DESCRIPTION
**Pull request by jaapmarcus**
- Add support for basic "White label" #2493
- Replace for example "ACCOUNT_READY" With the current translation. We might want to tweak them
- Updated translations where English was different from source for example: Editing web domain replaced by Edit web domain
- Dropped .mo for English 
- From email and name are changeable by user via settings (Form doesn't exists yet) 
- Removed all "Hestia Control Panel" text with %s. Except on /edit/server. There it is converted to hardcoded
- Option to hide docs
- Allow user to use custom templates for email (Fully editable and available in any supported languages
- Change / Update Subject  of said emails 
- Alter / change title
-

### CODE REVIEW

**Comment by myrevery** [comment]
@jaapmarcus Do we have an ETA?

**Comment by jaapmarcus** [comment]
Have decided to drop "logo" changing / update support.  The system I implemented was not great and still had issues. 

PR will very soon a merge hell and it would be useful to allow the "community" to start on translation work...

**Comment by jaapmarcus** [comment]
Screenshot 2023-04-27 at 00 28 22

**Comment by myrevery** [comment]
@jaapmarcus Request hold on the merge.

After reviewing all changes, some typos and missing strings were found.

If you accept, I'll make a PR to the "refactor-translation-strings" branch by next week, agree?

**Comment by jaapmarcus** [comment]
Please go ahead :)

**Review by AlecRust — APPROVED** [review]

**Comment by jaapmarcus** [comment]
Will merge it "tomorrow" and prepare https://translate.hestiacp.com/projects/hestiacp-1.8/ to be translated

**Comment by myrevery** [comment]
Still have to wait...

After testing the scan, it looks like there are still a lot of strings that need to be cleaned up.

**Comment by jaapmarcus** [comment]
> Still have to wait...
> 
> After testing the scan, it looks like there are still a lot of strings that need to be cleaned up.

The main issue for now any changes in the main branch on the "Web" page will cause merge conflict hell .. 

Really want to prevent this kind of *** if possible. 

Have synced up the current .pot file with https://translate.hestiacp.com/projects/hestiacp-1.8/

**Comment by myrevery** [comment]
I'll finish it ASAP...

**Comment by myrevery** [comment]
@jaapmarcus https://github.com/hestiacp/hestiacp/pull/3523 is ready to merge.

I noticed a lot of strings on GlotPress link to legacy "*.html" templates.

Seems like you need to clean up your dev machine before scanning.

**Pull request merged**
