### PR TITLE
[Feature] Nginx Fast CGI Cache support

### PR DESCRIPTION
**Pull request by jaapmarcus**
Adds support for all NGINX (Stand alone) users 

- Added 3 new commands 
v-add-web-domain-fast-cgi-cache user domain.tld 

Append "Yes"
v-add-web-domain-fast-cgi-cache user domain.tld yes 
For adding non required header (x-status) for debugging [hit / miss]

v-delete-web-domain-fast-cgi-cache user domain.tld 
Revert changes made to original and disables cache

v-purge-web-domain-nginx-cache user domain
Purges /var/cache/nginx/%domain% (Proxy) or /var/cache/nginx/php-fpm/%domain% (Fast CGI)

Updated all templates to support  fast-cgi-cache

Updated Web UI
Screenshot 2020-11-15 at 09 53 05

[*] Fixed also a minor bug in /web/template/user/edit_web.html "success" message was showing double

Thanks to @cmstew

### CODE REVIEW

**Comment by gabriel-curtino** [comment]
I will be awesome if you can set by the settings (at admin / server level) the value for the cache `max_size` and the `key_zone` size. :+1:

**Comment by jaapmarcus** [comment]
Key zone is by default the domain. Max size is maybe up for consideration

https://github.com/hestiacp/hestiacp/blob/d1f1fb891527a7bb5025ead708e3b2055d05a50f/bin/v-add-web-domain-fast-cgi-cache#L68-L70

**Comment by gabriel-curtino** [comment]
I'm referring to the size of the key_zone, that is hardcoded to 10 megabytes.

Nevermind! For special cases it can be tweaked by hand :+1: 

Thanks!!!

**Comment by jaapmarcus** [comment]
I just modified the versions so we are able to merge them. But you have maybe a point..

**Comment by vvcares** [comment]
@jaapmarcus 
Hi, is this option (Fast CGI selection), still avail in our latest hestia v.1.4.3 ?
Im using v1.4.3. But i dont see this option as mentioned above picture..

https://user-images.githubusercontent.com/9754650/99180665-6a44c900-2728-11eb-8519-ecd3e98b3108.png

**Comment by ScIT-Raphael** [comment]
@vvcares fcgi caching is only enabled in nginx, not in nginx+apache2.

**Comment by vvcares** [comment]
Ok guys. Thank you for your quickest response  :-)

**Pull request merged**
