### PR TITLE
Fix cpu architecture compatibility with b2 host

### PR DESCRIPTION
**Pull request by zedpr0**
Add check for cpu architecture and use the python b2 package instead of Github for arm64 architecture as the GitHub version doesn't exist and will produce an error.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
It should be also include in:

https://github.com/hestiacp/hestiacp/blob/e3c2147fb957dd585b39e11c93130a23063a2a2b/func/upgrade.sh#L551-L569

How I don't know how it will like to run pip3 during atp update... 

It is probably better to install always via pip(3) and make it always the same ...

**Comment by zedpr0** [comment]
I don't know how the apt upgrade will work either, but I think you're right we can just use pip3 for all cpu architectures and make it the same. I can edit the v-add-backup-host file and the upgrade.sh script to use pip3 only if you are okay with that.

**Comment by kpapad904** [comment]
> It is probably better to install always via pip(3) and make it always the same ...

It is generally considered bad practice to run `pip install` with root privileges, as it may interfere with system installed packages, in fact Fedora-family OSes have a warning about it.

There are also webpages discussing the issues e.g. https://www.getpagespeed.com/server-setup/do-not-run-pip-as-root

PS: Btw IMHO the backup tool best suited for HestiaCP (assuming a web-host where the same popular software is used by dozens of its sites) would be BorgBackup https://github.com/borgbackup/borg

**Comment by jaapmarcus** [comment]
Borgbackup is on a "Wishlist" 

I have created an issue report on the Backblaze repo

https://github.com/Backblaze/B2_Command_Line_Tool/issues/776

So if we are able to get it working maybe they can merge it ...

**Comment by kpapad904** [comment]
> So if we are able to get it working maybe they can merge it ...

Better for HestiaCP to keep using the official B2 binary (until they offer an apt repo)

And for the (few?) non-AMD64 HestiaCP installations, just install `b2` with pip3 & virtualenv

**Comment by ScIT-Raphael** [comment]
> > So if we are able to get it working maybe they can merge it ...
> 
> Better for HestiaCP to keep using the official B2 binary (until they offer an apt repo)
> 
> And for the (few?) non-AMD64 HestiaCP installations, just install `b2` with pip3 & virtualenv

+1, it sounds like the right solution.

**Review by ScIT-Raphael — CHANGES_REQUESTED** [review]
We decided to add a warning instead installing b2 over pip. As soon as b2 provides arm binarys, we'll include them.

**Comment by zedpr0** [comment]
> We decided to add a warning instead installing b2 over pip. As soon as b2 provides arm binarys, we'll include them.

I have edited the pull request to return an error instead.

**Pull request merged**
