### PR TITLE
Enhancement/exim advertise auth only on localhost and tls connections

### PR DESCRIPTION
**Pull request by sahsanu**
Right now, HestiaCP only provides out of the box auth login and auth plain authorization mechanisms to Exim. That means that if you connect to port 25 or port 587, the user will be able to use AUTH LOGIN or AUTH PLAIN to authenticate against the mail server and the password will be send in cleartext over the net.

With this PR, Exim will only advertise AUTH mechanism if you connect to it to localhost or the connection is already a TLS connection (after STARTTLS on ports 25 and 587 or implicit TLS on port 465).

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for your submission. In order for us to merge these changes, there needs to be a step added to the appropriate upgrade script (under /install/upgrade/versions/{version}.sh) so that existing installations are brought up to the same standard.

**Comment by sahsanu** [comment]
Hello @krismkenn, I've been using HestiaCP for only 3 weeks so my knowledge about it is pretty limited but I'm doing my best ;). I've added upgrade script 1.8.6.sh, I hope it has all the data you need, take a look and tell me if I need to add/modify/delete something.

**Comment by jaapmarcus** [comment]
We have some internal discussion about applying this change on update for existing installs.

It will break for sure any existing setup where users don't use tis / ssl

**Comment by sahsanu** [comment]
We could check first whether `tls_advertise_hosts = *` is defined and update current exim conf if it is, something like this:
```

if [ "$MAIL_SYSTEM" = 'exim4' ]; then
        if grep -q '^tls_advertise_hosts = \*' '/etc/exim4/exim4.conf.template'; then
                if ! grep -qw '^auth_advertise_hosts =' '/etc/exim4/exim4.conf.template'; then
                        echo '[ * ] Enable auth advertise for Exim only for localhost and TLS connections'
                        sed -i '/^tls_require_ciphers\s=\s.*/a auth_advertise_hosts = localhost : ${if eq{$tls_in_cipher}{}{}{*}}' '/etc/exim4/exim4.conf.template'
                        "$BIN"/v-restart-mail
                fi
        fi
fi
```

**Comment by jaapmarcus** [comment]
Every version since Hestia release has it already enabled...

https://github.com/hestiacp/hestiacp/blame/cba75321f01355d1e9f58e24efc3bc897dd36902/install/debian/exim4.conf.template
So many users will still encounter any issues if we just update it overnight. 

Probably disable the upgrade script for new setups I don't care really about it as users will need to setup it anyway then...

**Comment by sahsanu** [comment]
Ok, then it should be better to remove the upgrade script from the pull request.

I know the change to exim conf is just to add a line but, do you think it's worth to create a script and put it inside `install/upgrade/manual/` so the users can exexute it to add the directive in their current installation? If the answer is yes, I'll create it.

**Comment by jaapmarcus** [comment]
> 

Fine for me...

**Review by jaapmarcus — APPROVED** [review]

**Comment by sahsanu** [comment]
Ups, I was finishing the manual script right now but seems you created it already ;)

**Comment by jaapmarcus** [comment]
> Ups, I was finishing the manual script right now but seems you created it already ;)

Wanted to do the release now ...

**Pull request merged**
