### PR TITLE
Update documentation development instructions

### PR DESCRIPTION
**Pull request by jaapmarcus**
- Use yarn instead pnpm
- Update command

### CODE REVIEW

**Comment by jaapmarcus** [comment]
@AlecRust  If you have time please update the instructions for "Hestia development"

**Comment by wojsmol** [comment]
Update numbers in instruction in `docs/docs/contributing/development.md`

**Comment by jaapmarcus** [comment]
> Update numbers in instruction in `docs/docs/contributing/development.md`

vitepress should sort it out

https://docs-instructions.hestiacp-dev.pages.dev/docs/contributing/development

**Comment by imjuniper** [comment]
Not sure if it fits here, but we should probably add or edit issue templates to be applicable to documentation

**Comment by AlecRust** [comment]
> Update numbers in instruction in `docs/docs/contributing/development.md`

This is a Markdown feature to avoid needing to update all the numbers when a bullet point changes.

**Comment by jaapmarcus** [comment]
> Not sure if it fits here, but we should probably add or edit issue templates to be applicable to documentation

If you have an idea please go ahead ...

**Pull request merged**
