### PR TITLE
Fix sending issues due to mail rate implementation.

### LINKED ISSUE #2666: [Bug] Email account is sending too many emails - rate overlimit
### Describe the bug

The **Exim add custom ratelimits by user (#2225)** feature fails if the From email address doesn't match the Reply-To address (and the Reply-To address isn't a bona fide account).

For instance, if a client MTA tries to send an email through the smtpout@example.com account but with a noreply@example.com Reply-To value then the ratelimit condition will be tested with an illegal (blank) max message count value.  (See [exim ratelimit ACL syntax](https://www.exim.org/exim-html-current/doc/html/spec_html/ch-access_control_lists.html#SECTratelimiting).)

You will see something similar to this message in `/var/log/exim4/rejectlog` if you are experiencing this issue:

`2022-06-17 17:28:38 H=(server-mta) [203.0.113.69] X=TLS1.3:ECDHE_X25519__RSA_PSS_RSAE_SHA256__AES_256_GCM:256 CV=no F=<noreply@example.com> A=dovecot_login:smtpout@example.com rejected RCPT <trobinson@example.com>: Email account smtpout@example.com is sending too many emails - rate overlimit = 83.6 / 1h`

As an interesting distraction, you will be able to successfully send the exact same email from the HestiaCP web email interface (e.g. https://webmail.example.com)).  It turns out that HestiaCP configures exim to accept all smtp rcpt commands if they come from the local host, so the bad ratelimit test is never hit when sending through the web email page.

### Tell us how to replicate the bug

1. Create an email account (e.g. smtpout@example.com).
   - Usually through the Hestia MAIL page (e.g. https://hestiacp.example.com/list/mail/?domain=example.com)
2. Ensure some other account doesn't exist (e.g. noreply@example.com) to use as the Reply-To address.
3. Use your favorite client MTA to send an email to anyone you wish (e.g. myself@example.com).
   - I was able to reproduce the failure with [SMTPer](https://www.smtper.net/) online SMTP tester.
4. Observe failure.

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.6.0

### Operating system

Ubuntu 20.04.4 LTS (x86_64)

### Log capture

```shell
2022-06-17 17:28:38 H=(server-mta) [203.0.113.69] X=TLS1.3:ECDHE_X25519__RSA_PSS_RSAE_SHA256__AES_256_GCM:256 CV=no F=<noreply@example.com> A=dovecot_login:smtpout@example.com rejected RCPT <trobinson@example.com>: Email account smtpout@example.com is sending too many emails - rate overlimit = 83.6 / 1h
```

### PR DESCRIPTION
**Pull request by ScIT-Raphael**
Fixes #2666

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Review by jaapmarcus — CHANGES_REQUESTED** [review]
Add an "message" That issue has been fixed with rate limit

**Review by jaapmarcus — APPROVED** [review]

**Comment by mmoo9154** [comment]
@jaapmarcus, I don't want to come off as ungrateful, so I hope my comments don't offend.  I love HestiaCP, and it's obvious you dedicate a lot more time to the code than I am able to.  Thank you!

With that said, I don't know if I agree with this implementation/fix.  It does address the specific problem I am having.  But, the deeper issue is that the expression in this PR still has paths that can return a null/empty value.  The null value is what caused the original failure.

As written, the if test at line 141 in install/deb/exim/exim4.conf.template is not robust, and it's redundant.  A better expression would be:
```
          ratelimit = ${lookup {$authenticated_id} lsearch\
                          {/etc/exim4/domains/${domain:$authenticated_id}/limits}\
                          {$value}{DEFAULT_RATELIMIT}} / 1h / strict/ $authenticated_id
```
This simply attempts to lookup the per user ratelimit and if it fails for any reason, it uses the site default for the ratelimit.  There is no need to preflight the existence of the site's `limits` file.

This would allow the `/etc/exim4/domains/<domainname>/limits` file to be a lot smaller as well since you only need to store values for those users that have non-blank rate limits.

BTW, I was wondering why you used an $acl_c_... variable.  My reading of the docs says that those variables are used to pass values between ACLs and between different received messages.  This calculation is not used anywhere else and is recalculated fresh for each recipient.  It seems like using a variable name like `$per_user_ratelimit` might be safer (scoped more tightly) if you still wanted to set a variable explicitly and then use it in the ratelimit condition.

I changed the second half of the lsearch expression because using the `$sender_address_domain` to lookup the domain name suffers from the same problem as the original bug.  Though, it won't cause a problem unless the From and Reply-to addresses are on different domains.  Better to just use the domain directly from the `$authenticated_id` value that is used everywhere else and is used as the <key> in the ratelimit condition at line 142.

It seems like it might be better to evaluate the `${readfile{/etc/exim4/limit.conf}}` expression in the macro definition section of the config file and assign it to something like `DEFAULT_RATELIMIT` since that expression never change for any message or recipient.  Then the third line of the condition above can be `{$value}{DEFAULT_RATELIMIT}`.  (FWIW, I'm totally unclear on how exim macros are evaluated, so that might not reduce the number of times the `/etc/exim4/limit.conf` file is read.)

Lastly, naming the per site ratelimit file `limits` and the global one `limits.conf` I find distracting.  I'd name them the same, and I'd probably name them ratelimit.conf since the generic name 'limits' implies to me that it stores all configurable limits.  Others may disagree, but I think naming is important, though this is just a gentle observation more than a strong opinion.

I'm quite new to exim config file magic, so I apologize if this wouldn't work for some reason.  I am at work and I am unable to cut over to exim to make sure.

**Comment by jaapmarcus** [comment]
> 
> ```
>           ratelimit = ${lookup {$authenticated_id} lsearch\
>                           {/etc/exim4/domains/${domain:$authenticated_id}/limits}\
>                           {$value}{DEFAULT_RATELIMIT}} / 1h / strict/ $authenticated_id
> ```

Exim 4.94 change a lot with the tained filename  "crap"

Issue "method" will be "Tainted filename for search '/etc/exim4/domains/domain.com/limits'" 

How ever it looks way better then the current method.

**Comment by jaapmarcus** [comment]
>This would allow the /etc/exim4/domains/<domainname>/limits file to be a lot smaller as well since you only need to store values for those users that have non-blank rate limits.

Would it matter a lot?  
>BTW, I was wondering why you used an $acl_c_... variable. My reading of the docs says that those variables are used to pass values between ACLs and between different received messages. This calculation is not used anywhere else and is recalculated fresh for each recipient. It seems like using a variable name like $per_user_ratelimit might be safer (scoped more tightly) if you still wanted to set a variable explicitly and then use it in the ratelimit condition.

In  ${eval:$acl_c_msg_limit / 2} / 1h / strict / $authenticated_id we use also to warn the user to if they send more mails then 50% of there limit


>It seems like it might be better to evaluate the ${readfile{/etc/exim4/limit.conf}} expression in the macro definition section of the config file and assign it to something like DEFAULT_RATELIMIT since that expression never change for any message or recipient. Then the third line of the condition above can be {$value}{DEFAULT_RATELIMIT}. (FWIW, I'm totally unclear on how exim macros are evaluated, so that might not reduce the number of times the /etc/exim4/limit.conf file is read.)


Makes sense...

**Comment by mmoo9154** [comment]
Not sure I understand what you are trying to say with the 'Exim 4.94 change a lot with the tained filename "crap"'.  Sorry 😬

I see that the `${lookup {<key>} <search type> {<file>} {<string1>} {<string2>}}` will fail with an error message if the `<file>` does not exist.  Sorry again.  As I mentioned, I wasn't able to test my suggestion while I was at work.  I see why you have the `${if exists{<file name>}}` test now.

I was also completely unfamiliar with the notion of "taint" during exim config processing.  Thank you for bringing that to my attention.

Is the value of `$authenticated_id` or `$authenticated_sender` considered tainted?  I couldn't find any documentation either way.

I did find a section under [2. The AUTH parameter on MAIL commands](https://www.exim.org/exim-html-current/doc/html/spec_html/ch-smtp_authentication.html#SECTauthparamail) that says:

    Do not confuse $authenticated_sender value with $authenticated_id, which is a string obtained
    from the authentication process, and which is not usually a complete email address.

The wording is a little ambiguous, but I read it to say that `$authenticated_id` *is* a complete email address when it is not blank.

Does anyone know if `$authenticated_id` can be blank under any reasonable HestiaCP usage scenario?  If so, we might need to cover that case.

**Comment by mmoo9154** [comment]
Thanks for reminding me about the warning.  Would it make more sense to use `$acl_m_msg_limit` instead of `$acl_c_msg_limit`?  I velieve the `$acl_m...` variables have a shorter lifespan than `$acl_c...` variables.

**Comment by jaapmarcus** [comment]
With changes in exim 4.94.4 (Debian 11 and Ubuntu 22.04 (4.94.5)) changes have ben made that "doesn't allow direct access from an variable... 

https://mox.sh/sysadmin/tainted-filename-errors-in-exim-4.94/

It complicates a lot of things...

**Comment by plutocrat** [comment]
I can confirm that this is a bug, as I have a client suffering from it. It does indeed seem to be related to the fact he is using an alias to login. Glad you guys are on top of it. 
Would you suggest editing the exim config with the fix suggested by mmoo above, or just sit tight and wait for the fix to roll out?

**Comment by jaapmarcus** [comment]
Changes proposed in https://github.com/hestiacp/hestiacp/pull/2676/commits/e5bcfbdd90568196893d97a7c681969aad126cdc

Work fine. 

I need to check what exactly need to change so we can get it working for the changes @mmoo9154  proposed. But it will take a few hours...

**Comment by jaapmarcus** [comment]
Let move the discussion first to:
https://github.com/hestiacp/hestiacp/issues/2666

**Pull request merged**
