### PR TITLE
Fix for mass adoption

### PR DESCRIPTION
**Pull request by anvme**
Removed FastCGI Cache

### CODE REVIEW

**Review by jaapmarcus — COMMENTED** [review]
With the changes you made fast cgi is still enabled:

Removing https://github.com/hestiacp/hestiacp/blob/8e1f5ed9215f1cb4f836985b46ecd9e2abc49edf/install/deb/templates/web/nginx/php-fpm/craftcms.stpl#L51 

In both templates should be enough

**Comment by anvme** [comment]
If we remove only include %home%/%user%/conf/web/%domain%/nginx.fastcgi_cache.conf*; 
Admin page will no work.
This line must be there

**Comment by anvme** [comment]
I remove Craft CMS specific settings from nystudio107

**Comment by jaapmarcus** [comment]
> If we remove only include %home%/%user%/conf/web/%domain%/nginx.fastcgi_cache.conf*;
> Admin page will no work.
> This line must be there

File doesn’t exsists on default so removing should be no issue

**Comment by anvme** [comment]
@jaapmarcus here we go?

**Pull request merged**
