### PR TITLE
Adds sticky footer & theme header metadata

### PR DESCRIPTION
**Pull request by rmj-s**
Adds support for theme header metadata
Adds new base buttons
Updates app installer page styling

### CODE REVIEW

**Comment by ghost** [comment]
Hi @rmj-s,

Thanks for your pull request. I'll be placing this one on hold until after v1.1.0 is available, as it is being prepared for release next week; the merge window for functionality changes has closed and only last minute bug fixes can be included at this point.

**Comment by rmj-s** [comment]
@kristankenney,
You can merge it whenever you think its right, but do expect a large number of pull requests from me for UI. Do you have any UI improvement plans after releasing v1.1.0? Also will you be able to push a theme with this release? I've one ready.

**Comment by ghost** [comment]
Hi again @rmj-s,

Please submit your pull requests when ready, and we will review them for potential inclusion. While we appreciate all contributions to the project, we can not guarantee that all pull requests will be approved or merged, based on the process that our core team follows.

We won't be including any user-contributed themes in 1.1.0 as the interface has already been locked down for documentation purposes.

**Comment by rmj-s** [comment]
@kristankenney 
Is there any ETA by when I can expect a decision on this?

**Comment by ScIT-Raphael** [comment]
Currently, we do not have any eta yet, we're currently preparing the roadmap for 1.1.1 and all feature releases of hestia.

**Comment by ghost** [comment]
Hi @rmj-s,

We've decided not to merge this PR at this time, as we believe there is no need to constantly display the version or copyright at the bottom of the page.

**Pull request closed without merging**
