### PR TITLE
Quick install namelessmc

### PR DESCRIPTION
**Pull request by MCJUNIORLK**
Here is the first quick install app I made. Hope everything works out that way. (Hope I'm doing this right with the PR)

### CODE REVIEW

**Review by Anuril — APPROVED** [review]
Looks good to me, I've tested the installation and it worked. I also tested installing on http and switching to https afterwards, so that's also fine.

**Comment by Anuril** [comment]
@MCJUNIORLK could you run prettier on the file ? 
`npx prettier --write web/src/app/WebApp/Installers/NamelessMC/NamelessMCSetup.php`

**Comment by misternovel** [comment]
Hi guys! Wonderfull project! Like!! Plz add **_WeKan_** https://wekan.github.io/ in quick install. 10x!

**Comment by jaapmarcus** [comment]
Will not work ..

> Hi guys! Wonderfull project! Like!! Plz add **_WeKan_** https://wekan.github.io/ in quick install. 10x!

Install WeKan ® Server v7.55, Meteor 2.14, [Node.js 14.21.4](https://github.com/wekan/node-v14-esm/releases/tag/v14.21.4), MongoDB 6.0.16
Won't work via Quick install app

**Review by ScIT-Raphael — APPROVED** [review]

**Pull request merged**
