### PR TITLE
Fallback to Russian instead of English for Ukranian

### LINKED ISSUE #4644: [Bug] File manager language
### Describe the bug

Problem with changing language in file manager

### Tell us how to replicate the bug

Everything worked out. It works as it should.

There is a problem with the file manager language. As I understand it, the language should be set depending on which one the user has installed.

The panel has Ukrainian, but the file manager is in English.

I tried changing the parameter in configuration.php:

if (!empty($_SESSION["language"])) {
$lang = $_SESSION["language"];
} elseif (!empty($_SESSION["LANGUAGE"])) {
$lang = $_SESSION["LANGUAGE"];
} else {
$lang = "ru";
}

It didn't help. What should I do?
I added a Ukrainian translation to filegator in github.
At the moment, the problem is that when I force the language to ru, nothing happens. The language remains English.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

v1.9.0~beta

### Operating system

Debian 12

### Log capture

_No response_

### PR DESCRIPTION
**Pull request by jaapmarcus**

### CODE REVIEW

**Comment by jaapmarcus** [comment]
For permanent fix we should wait for:
https://github.com/filegator/filegator/pull/502

**Comment by jekasumy** [comment]
> For permanent fix we should wait for: [filegator/filegator#502](https://github.com/filegator/filegator/pull/502)

Language officially added to filegator
Now you can correct the file manager language in the control panel

**Comment by jaapmarcus** [comment]
Friday I will uodate it ...

**Comment by jaapmarcus** [comment]
Screenshot 2024-11-28 at 20 30 29

Exit to control panel / Sytemadministrator are hard coded ...

**Comment by jekasumy** [comment]
> Screenshot 2024-11-28 at 20 30 29
> Exit to control panel / Sytemadministrator are hard coded ...

No way to translate?

**Pull request merged**
