### PR TITLE
Further UI tidy

### PR DESCRIPTION
**Pull request by AlecRust**
- ".vst-text" is used everywhere but does nothing in majority of cases
- ".step-top" and ".input-label" are just padding top utility classes, sometimes used together (cancelling each other out)

This PR simplifies the HTML by reducing combined usage of these classes, and renaming them to be clear what they do.

e.g. "vst-text input-label step-top" has been replaced with equivalent "u-pt18" for "padding top 18px".

This should make future migration of text inputs a bit easier.

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]
👍🏼

**Comment by AlecRust** [comment]
Not sure why CI failure 🤷‍♂️

**Comment by gOOvER** [comment]
> Not sure why CI failure 🤷‍♂️

funny error :D

`not ok 39 Restore[1]: Vesta archive for a non-existing user`

**Comment by gOOvER** [comment]
is the name: 

vestia.css

really correct?

**Comment by ScIT-Raphael** [comment]
> > Not sure why CI failure 🤷‍♂️
> 
> funny error :D
> 
> `not ok 39 Restore[1]: Vesta archive for a non-existing user`

we have a test which restores a vesta backup, so far so good, sometimes it can fail (no idea why).



> is the name:
> 
> vestia.css
> 
> really correct?

and yes, thats indeed correct. The vesta like theme is called vestia :).

**Comment by gOOvER** [comment]
> and yes, thats indeed correct. The vesta like theme is called vestia :).

ah ok :D learned something new :D

**Comment by jaapmarcus** [comment]
> > Not sure why CI failure 🤷‍♂️
> 
> funny error :D
> 
> `not ok 39 Restore[1]: Vesta archive for a non-existing user`

In about 20% it randomly files on one of the 6 restore tests have no idea why

**Pull request merged**
