### PR TITLE
Customization of the file manager with interface improvements

### PR DESCRIPTION
**Pull request by MaxiZamorano**
Improved interface for the file manager with the following improvements:

- Each row in the file manager table now alternates in color to make it easier to view data.
- Icons that represent whether it is a folder or a file.
- Reduced row size to provide a more compact and general view of files.
- Changes apply to both the light and dark versions.

**After:**
fm-1

**Before:**
fm-3

**After:**
fm-2

**Before:**
fm-4

### CODE REVIEW

**Comment by divinity76** [comment]
Could you add some before-after pictures of the same folder?

**Comment by MaxiZamorano** [comment]
> Could you add some before-after pictures of the same folder?

Yes, I edited it and now there is the before and after.

**Comment by imjuniper** [comment]
The edits looks alright to me, especially considering we can't really edit the markup it's styling anyways. However, are all the `!important` really necessary? It's kind of a nuke option when nothing else works usually...

**Comment by MaxiZamorano** [comment]
> The edits looks alright to me, especially considering we can't really edit the markup it's styling anyways. However, are all the `!important` really necessary? It's kind of a nuke option when nothing else works usually...

Most of them require `!important` since the filegator styles come after and give them preference, in some classes like ::before it may not be necessary and could be removed since they are new and do not exist in the filegator css, but since practically everything required `!important` I added them to everything to make it faster.

**Comment by imjuniper** [comment]
Yeah okay, I get that. I wish there was a better way, but oh well. Works for me!

**Review by imjuniper — APPROVED** [review]

**Comment by jaapmarcus** [comment]
Looks great. Just pushed an update to the latest Filegator to see if it keeps working....

**Pull request merged**
