### PR TITLE
Install sshd config: Remove previous DebianBanner override, include in update

### PR DESCRIPTION
**Pull request by vestacp-user**
New pull to replace #986 

1) Removing the previously imposed `DebianBanner no` from the install

As per @ioannidesalex request for sshd_config (2 & 3) :

2) Retaining HestiaCP imposed `LoginGraceTime 1m`.  Code should be made more robust and used in both the install and update scripts.  See my comments.  

3) Updates should normalize the sshd_config file to the desired current HestiaCP Install standard.  This can be risky, but I have added a v-script to do this and added some comments on how ensure robust code.  

Final Nice to Have:

4) Maybe add the run of the v-script to the log?  See my comment at the bottom of the new v-script.

I will wait for futher feedback on this before making the code robust because the HestiaCP team may wish to take this over and make it to their liking or request a different approach for my pull.  I still reccommend the general approach of making only the absolute minimum changes to the sshd_config file, but when required, it should be robust and changes commented and marked HestiaCP for transparency and tracebility.  (eg # Added/Deleted/Changed by HestiaCP (with timestamp ideally)

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Why creating a additional v-update-sshd-config when it is only one time use?

This is list is already large enough with scripts.

Just execute the command once in latest.sh and you are fine 

The other function as used almost every time and therefore use full as executeable for further uses..

**Comment by ghost** [comment]
@jaapmarcus I disagree; the intention of `v-update-sshd-config` in this case is to ensure that the SSH daemon configuration is in a known good state as mentioned by @vestacp-user and aligns with our goal of having a self-healing system. We can call this in the new upgrade system during rebuild the same as we do with rebuilding user configuration.

**Comment by vestacp-user** [comment]
As much as I prefer to minimize and simplify code, as @ioannidesalex and @kristankenney  indicates, if HestiaCP is to play in a system config file, it should be done in a very robust, safe, transparent and self-healing way.  This will reduce future code maintenance, bug fixes and end user support efforts over the long term.

**Comment by ghost** [comment]
Proceed with your work on making the config file handling more robust and we'll be happy to further review.

**Comment by vestacp-user** [comment]
For reference, if a system admin really does not want HestiaCP to change a file and the system admin really knows what they are doing, they can set `chattr -i` on the file.

For all other users, HestiaCP should take on full lifecycle responsability of the specific changes made to system files.

**Comment by vestacp-user** [comment]
A quick summary of this modified propoal:

Use `augtool` for modifications to config files.  This package is relatively common and included in both Debian and Ubuntu distros. This  will reduce HestiaCP code, bugs, maintenance, support, etc.

Always make a local versioned backup of the config file if it has changed since the last backup.  Standard `cp -u --backup=t` command, thus low risk, maintenance, code and high transparency.

I did not put `/etc/ssh/sshd_config` in a variable because it is only used twice and this path is very stable across most distros and over time.  It is explicit in `man sshd_config`

I put the `sshd_config_augtool=/files/etc/ssh/sshd_config` in a variable because it is used several times and it's occurrence of use could increase over time.

I have not touched the `Subsystem sftp` for now, but should be converted to augtool if this approach is retained.

If this approach is retained, the config file backup and use of `augtool` should be used going forward whenever possible.

Eventually, there should be an intregration between the install scripts, the package and the v-update scripts to avoid all the code duplication.   On example, but not the only solution, is a full `git clone` (or wget) of the project into /tmp/hestia/ at the beginning of the install script to have access to the v-* scripts and a bunch of other stuff to avoid code duplication.

**Comment by jaapmarcus** [comment]
I agree we should start using a "tool" for manipulating config files. There where some discussing about using Crutini but nothing set in stone...

**Comment by vestacp-user** [comment]
@jaapmarcus I didn't find `crutini` in Debian Repos, do you have a link?  

augeas is also used by puppet, saltstack, certbot (letsencrypt), etc.   It's seems to be the safest, simplest and lightest choice for now.

**Comment by jaapmarcus** [comment]
I was wrong 

Try crudini

**Comment by vestacp-user** [comment]
For reference here are the popcorn for both packages.  This is informative to see if the packages are used alot and if they will be well maintained, stable, secure and long lifespan.  

I would reccommend augeas, but I will wait for the Hestia's team guidance on this.

https://qa.debian.org/popcon.php?package=augeas (approx. 30,000)
https://qa.debian.org/popcon.php?package=crudini (approx. 100)

**Comment by jaapmarcus** [comment]
All  sugested changes have been implemented will close the pull request

**Pull request closed without merging**
