### PR TITLE
Add web domain button fix

### PR DESCRIPTION
**Pull request by rmj-s**
This commit fixes:
~~1. Incorrect template included when the user is logged in using login as.~~
2. Removed add web domain button when the package contains 0 domains,
#744 Add Web Domain button is now removed when the package has 0 domains, the redirect wasn't used due to uncertainty over other package options.

### CODE REVIEW

**Comment by Lupul** [comment]
Hello @rmj-s and thanks for your PR.

Some points after taking a quick first look:
- I see some formatting changes eg: striped whitespaces, indentation. Please don't mix functional changes with style changes, as it's more difficult to parse the relevant code changes.

- (Related to 1.) The nested if/else [here](https://github.com/hestiacp/hestiacp/pull/829/files#diff-da08438949207e39e2cbcbd13eca6d47R157-R166) seems unnecessary complicated and also I don't understand the problem it solves.
Currently when using login_as, the page body tpl is searched in the user tpl folder and if missing it's included from the admin folder. Admin user always uses the template from admin tpl folder. 

- (Related to 2.) I see you are comparing [here](https://github.com/hestiacp/hestiacp/pull/829/files#diff-25eb20c5898ec74fa9b487f519089458R10) `$panel[$user]['WEB_DOMAINS']` with the literal string '0', you should replace that with:
```php
if ( intval($panel[$user]['WEB_DOMAINS']) > 0 ) {
```

Otherwise the fix for 2. looks valid.

**Comment by rmj-s** [comment]
Hi @Lupul,
Thanks for the quick reply.

A. If you are referring to these [a](https://github.com/hestiacp/hestiacp/pull/829/commits/47f7f6ad7fdbcdadd08345d04a04c27f73a06bc0#diff-25eb20c5898ec74fa9b487f519089458L61), [b](https://github.com/hestiacp/hestiacp/pull/829/commits/47f7f6ad7fdbcdadd08345d04a04c27f73a06bc0#diff-25eb20c5898ec74fa9b487f519089458L61), [c](https://github.com/hestiacp/hestiacp/pull/829/commits/47f7f6ad7fdbcdadd08345d04a04c27f73a06bc0#diff-b9d64e24b51f3069c1cce68bcf824744L48), then these were caused by Atom, I apologize for this, I'll take care of it next time.

~~B. As seen [here](https://github.com/hestiacp/hestiacp/blob/5d7cf06e9a15e1d7d06d195be80d32a2914f0629/web/login/index.php#L24) and [here](https://github.com/hestiacp/hestiacp/blob/5d7cf06e9a15e1d7d06d195be80d32a2914f0629/web/inc/main.php#L103) while using login_as the session is always owned by admin and the login_as user get added to `$_SESSION['look']`, but as seen [here](https://github.com/hestiacp/hestiacp/blob/5d7cf06e9a15e1d7d06d195be80d32a2914f0629/web/inc/main.php#L157) we are only checking `$_SESSION['user']` which will always be `admin` when using login_as and hence only admin templates will be loaded.~~

~~C. Fixing~~

**Comment by jaapmarcus** [comment]
> B. As seen [here](https://github.com/hestiacp/hestiacp/blob/5d7cf06e9a15e1d7d06d195be80d32a2914f0629/web/login/index.php#L24) and [here](https://github.com/hestiacp/hestiacp/blob/5d7cf06e9a15e1d7d06d195be80d32a2914f0629/web/inc/main.php#L103) while using login_as the session is always owned by admin and the login_as user get added to `$_SESSION['look']`, but as seen [here](https://github.com/hestiacp/hestiacp/blob/5d7cf06e9a15e1d7d06d195be80d32a2914f0629/web/inc/main.php#L157) we are only checking `$_SESSION['user']` which will always be `admin` when using login_as and hence only admin templates will be loaded.

When I as "admin" login in from the admin account  to an user account always the admin templates should be loaded. 

For example I need to change the default template for user.com I need to login as the user via the "login_as" function and edit the web domain and change the template therefore the "admin" templates should be loaded. In your proposed change the user template should be loaded without the functionalities.

**Comment by rmj-s** [comment]
@jaapmarcus thanks for letting me know that use case. I have reverted those changes.
@Lupul I have removed the render function changes, spacing and indentation issues. Further
 `if (intval($panel[$user]['WEB_DOMAINS']) > 0)`  can't be used as we have option for `unlimited` domains also, So I have used `if (intval($panel[$user]['WEB_DOMAINS']) > 0 || $panel[$user]['WEB_DOMAINS'] == 'unlimited')`

**Comment by Lupul** [comment]
There is still a extra indent in list_user.html

**Comment by rmj-s** [comment]
> There is still a extra indent in list_user.html

I have intentionally added an indent [here](https://github.com/hestiacp/hestiacp/pull/829/files#diff-25eb20c5898ec74fa9b487f519089458R16) because it was incorrectly indented when added in [this](https://github.com/hestiacp/hestiacp/commit/ed0e802861b5bdf27669879e018ae516630357ba#diff-25eb20c5898ec74fa9b487f519089458R12) commit, should I revert that and create a separate PR for it?

**Comment by Lupul** [comment]
yes, but no need to revert, just make the changes on you local branch and push a new commit, all furter commits that you add in your local branch will be visible here too (after pushing them)

**Comment by rmj-s** [comment]
@Lupul,
I hope it is fine now, do you follow PSR-12 for Hestia?

**Comment by Lupul** [comment]
I'm afraid it's not, I agree there are inconsistent indents and need to be fixed, but let's keep style fixes for another PR, I want to see only the relevant/fixed code here.
image

**Comment by ScIT-Raphael** [comment]
As @lupul requested, please open a new pull request with only the relevant change/commit. Going to close this one.

**Pull request closed without merging**
