### PR TITLE
Fix: "Warning: The type attribute for the script and link element is not needed and should be omitted."

### PR DESCRIPTION
**Pull request by s0t**

### CODE REVIEW

**Comment by s0t** [comment]
Fix php style
Update jquery

**Comment by jaapmarcus** [comment]
Current system of loading the custom / non default theme cause a lot of errors in the nginx-error.log

Maybe replace it with something like this 
```
<?php 
    if ($selectedTheme !== 'default') {
        if (file_exists($_SERVER['HESTIA'] .'/web/css/themes/' . $selected_theme . '.min.css')) {
            $css = '/css/themes/' . $selected_theme . '.min.css';
        }else{
            if (file_exists($_SERVER['HESTIA'] .'/web/css/themes/custom/' . $selected_theme . '.min.css')) {
                $css = '/css/themes/custom/' . $selected_theme . '.css';
            } else {
                $css = '/css/themes/custom/' . $selected_theme . '.css';
            }
        }
?>
  <!-- Load HestiaCP  themes (minified, updated/overwritten with updates) - ($HESTIA/web/css/themes/*.min.css) -->
  <!-- Load Custom themes https://docs.hestiacp.com/customize_hestia.html - ($HESTIA/web/css/themes/custom/*.(min.)css) -->  
  <link rel="stylesheet" href="<?=$css; ?>?<?=rand(); ?>" rel="preload" />
<?php } ?>
```

**Comment by s0t** [comment]
> Current system of loading the custom / non default theme cause a lot of errors in the nginx-error.log
> 
> Maybe replace it with something like this
> 
> ```

>    if ($selectedTheme !== 'default') {

this variable is undefined

**Comment by jaapmarcus** [comment]
I have merged this pull request in a new one https://github.com/hestiacp/hestiacp/pull/1899 will close this one

**Pull request closed without merging**
