### PR TITLE
Add edit button to suspended cron job

### PR DESCRIPTION
**Pull request by fsolutions**
It's not usefull to disable edit button of suspended cron job.

### CODE REVIEW

**Review by jaapmarcus — COMMENTED** [review]
Even after enabling editing changing cronjob in web UI a check in v-change-cronjob still prevent the cronjob from editing. 



https://github.com/hestiacp/hestiacp/blob/2ee38eb76870b2ab4e62ac55c560fdd80f188732/bin/v-change-cron-job#L45

after saving it will also unsuspend them. 

https://github.com/hestiacp/hestiacp/blob/2ee38eb76870b2ab4e62ac55c560fdd80f188732/bin/v-change-cron-job#L61

**Comment by fsolutions** [comment]
> Even after enabling editing changing cronjob in web UI a check in v-change-cronjob still prevent the cronjob from editing.
> 
> https://github.com/hestiacp/hestiacp/blob/2ee38eb76870b2ab4e62ac55c560fdd80f188732/bin/v-change-cron-job#L45
> 
> after saving it will also unsuspend them.
> 
> https://github.com/hestiacp/hestiacp/blob/2ee38eb76870b2ab4e62ac55c560fdd80f188732/bin/v-change-cron-job#L61

It's allright. The main problem for me was to look what cronjob was hidden in suspended line. Now i can do it. 
I understand, that the best desicion is enabling to unsespend cronjob from its page, but it is not necessarily.

**Comment by jaapmarcus** [comment]
> It's allright. The main problem for me was to look what cronjob was hidden in suspended line. Now i can do it. I understand, that the best desicion is enabling to unsespend cronjob from its page, but it is not necessarily.

It that case it probably it make sense to adjust the contrast in the table it self. It will only not help in the case of long commands

**Comment by ScIT-Raphael** [comment]
Hi, thank you for your PR - as you may noticed, it wasnt merged for a long time because there was a discussion "do we want to implement it or not", including multiple reviews where we either decided to "not yet" or "lets check it later". We did now another review round and decided to close your PR and not implement the change. We appreciate your work and effor, but we do not see a need to implement the related change.

**Pull request closed without merging**
