### PR TITLE
Fix for "Connection to storage server failed." dovecot error

### PR DESCRIPTION
**Pull request by Pleskan**
This pull request contains fix for annoying [**Connection to storage server failed**](https://forum.vestacp.com/viewtopic.php?t=13539) dovecot error,  while user trying to login to Roundcube GUI. This fix is tested under Ubuntu 16.04.5

### CODE REVIEW

**Comment by ghost** [comment]
Hi @Pleskan,

Thanks for submitting this PR to our team. I haven't seen this come up when connecting to Roundcube on an Ubuntu 18.04.2 LTS-based server -- is this issue specific to Ubuntu 16.04 that you're aware of?

In reviewing the commits, I took notice that the namespace prefix is labelled as **mail/** for 14.04 and 18.04, while 16.04's conf file specifies **/mail** and want to verify if this is intended?

Thanks again for your contribution to Hestia, your feedback and work is appreciated.

**Comment by ioannidesalex** [comment]
I wasn't able to replicate this either.

**Comment by Pleskan** [comment]
@kristankenney Hi!
Yes, I've faced this issue many times while running VestaCP on Ubuntu 16.04.x
For example in VestaCP [config](https://github.com/serghey-rodin/vesta/blob/master/install/ubuntu/16.04/dovecot/dovecot.conf) there is no prefix at all. Thus I have no idea about slash position at the prefix string (starting or trailing). Moreover I don't test default config of VestaCP on Ubuntu 18.04 because of bugs of Vesta. So, unfortunately I can not give you some useful info, but everything I know that subject fix for ubuntu 16.04 works well at dozen VPS. I can give you access to a test vps with ubuntu 16.04 in a few days (this weekend) to convince communtity that bug exists.

**Comment by ghost** [comment]
@Pleskan, thanks for getting back to me -- I'll spin up a VM with Ubuntu 16.04 this weekend to test/replicate and keep you posted. :)

**Comment by Pleskan** [comment]
@kristankenney If you talking about [this ](https://github.com/hestiacp/hestiacp/pull/214/commits/81c01d9ce9fde390303ab5dfc79e280c8d7c5ac2) commit thats is my fault: it's just a typo.

**Comment by Pleskan** [comment]
So, correct position of the slash is at the end of word, like this **mail/**

**Comment by ghost** [comment]
Hi @Pleskan, after further testing we're still unable to reproduce this issue using the latest build of hestia on Ubuntu 16.04.5.

Please try installing the latest release from the master branch and let us know if the issue with Roundcube persists -- I'll go ahead and close this PR for the time being.

**Comment by Pleskan** [comment]
@kristankenney, dovecot log from clean server with Ubuntu 16.04.5 (Digital Ocean image) is below.
`Mar 17 19:03:31 master: Warning: Killed with signal 15 (by pid=3320 uid=0 code=kill)
Mar 17 19:03:31 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Mar 17 19:04:04 imap-login: Info: Login: user=<tester@mautik.tk>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=3352, secured, session=<LThjQk2EdI5/AAAB>
Mar 17 19:04:04 imap(tester@mautik.tk): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Mar 17 19:04:04 imap: Error: Invalid user settings. Refer to server log for more information.`
I can give you root SSH/Hestia  admin access to that test VPS.

I'm looking forward for your feedback

**Comment by Pleskan** [comment]
@kristankenney, here is screenshot https://prnt.sc/mz45wi

**Pull request closed without merging**
