### PR TITLE
Update account.md

### PR DESCRIPTION
**Pull request by vdbhb59**
Added FreeOTP+ as another 2FA app, completely open sourced & available at F-Droid as well.

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]
Removed Ravio OTP

**Comment by vdbhb59** [comment]
OOC, when does the official website get updated? The changes are not reflecting there.

**Comment by vdbhb59** [comment]
The changes are still not reflecting on the documentation. Do I need to make more changes anywhere else?

**Comment by jaapmarcus** [comment]
They will be published when we make the next release...

**Comment by vdbhb59** [comment]
Ahh okay. I was not aware of that.
Thanks. :+1:

**Pull request merged**
