### PR TITLE
Disable ssl_early_data 

### PR DESCRIPTION
**Pull request by jaapmarcus**
https://datatracker.ietf.org/doc/html/rfc8470

@myrevery any ideas about it?

### CODE REVIEW

**Comment by jaapmarcus** [comment]
image

**Comment by jaapmarcus** [comment]
It seems to be safe for Static files and improving the speed

But not for php applications and so on and make it vulnerable for

**Comment by jaapmarcus** [comment]
https://english.ncsc.nl/publications/publications/2021/january/19/it-security-guidelines-for-transport-layer-security-2.1

**Comment by myrevery** [comment]
The benefits outweigh the risks.

I haven't had enough time to add protection to the application layer, but I will add it soon...

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3692

**Pull request closed without merging**
