### PR TITLE
Hide DNS option in list mail when DNS is disabled

### PR DESCRIPTION
**Pull request by ricardo777**
Hide the DNS icon in list mail page, when DNS is disabled.

### CODE REVIEW

**Review by AlecRust — APPROVED** [review]

**Comment by jaapmarcus** [comment]
DNS options need to be visible when users no DNS is available this will allow the users to copy over the DNS records and use it in Cloudflare or their DNS provider so they can create the correct SPF / DKIM record

**Comment by jaapmarcus** [comment]
Screenshot 2024-06-17 at 13 48 24

I assume we are talking about  this icon?

**Comment by ricardo777** [comment]
Ah I thought there was a good reason for it, is it not better to then list it as read only option?

**Comment by ricardo777** [comment]
> Ah I thought there was a good reason for it, is it not better to then list it as read only option?

Yes that is the icon

**Comment by jaapmarcus** [comment]
> Ah I thought there was a good reason for it, is it not better to then list it as read only option?

That might be an idea. But removing it now way ...

**Pull request closed without merging**
