### PR TITLE
Resolve #3684 Nginx 1.25.1+ Listen ... http2" directive is deprecated

### LINKED ISSUE #3684: [Bug] Nginx 1.25.1+ Listen ... http2" directive is deprecated
### Describe the bug

Update Nginx to 1.25.1 and restart server

[warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead

### Tell us how to replicate the bug

Update Nginx to 1.25.1 and restart server

[warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead

Changes required is to replace:
```
    listen      5.9.186.106:443 ssl http2;
```

With
```
    listen      ip:443 ssl;
    http2 on;
```

We should probally convert all the templates and sed them to the 1.25.0 pre format if nginx 1.25.0 or earlier is detected

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.x.x

### Operating system

N/A 

### Log capture

```shell
Update Nginx to 1.25.1 and restart server

[warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead
```

### PR DESCRIPTION
**Pull request by jaapmarcus**
+ Fallback for Nginx 1.25.0 and lower

Still suggest user to upgrade to the latest nginx version

### CODE REVIEW

**Comment by myrevery** [comment]
@jaapmarcus We can have the ability to automatically update NGINX for users.

Supporting multiple NGINX versions would be a heavy maintenance burden.

I created [1.7.8.sh](https://github.com/myrevery/hestiacp/blob/hotfix/nginx-http2-directive-issue/install/upgrade/versions/1.7.8.sh) based on "release" branch, do you accept this solution?

**Comment by jaapmarcus** [comment]
We have 4 "kind" of users:

- We have auto update Hestia users who will update only Hestia. This will work fine 👍🏼 
- We have users that will are up to date with every thing..  This shouldn't be needed....
- Users that are x versions behind. After we have released 1.8.0 the server will crash ...  As it might be not updated when the new templates dropped... It should restore it self after the full upgrade has been done..  
- Users that have their own build Nginx version or use it from a different apt source that maybe x version behind on Nginx...

We have about 45k unique servers pinging our APT server(s) every day and  a few days after x.x release only about 20k  users. 

With the patch I made at least for every setup it work fine. Other option is to wait a few months and hope the users in the mean time...

**Comment by myrevery** [comment]
I accept.:handshake:

But regarding where to set the new "http2" directive, I suggest that we should put it in "http" block instead of every "server" block.

This is to avoid issues when processing templates, as we can't predict the format of custom templates created by users.

But the syntax of the "listen ..." directive is normalized, so we can safely change its parameters.

What do you think?

Suggested changes to "func/domain.sh":
```
# "http2-directive.conf" also as the flag with new version, avoid call the nginx binary every time

if [ -e /etc/nginx/conf.d/http2-directive.conf ]; then
	while IFS= read -r old_param; do
		new_param="$(echo "$old_param" | sed 's/\shttp2//')"
		sed -i "s/$old_param/$new_param/" "$conf"
	done < <(grep -E "listen.*(\bssl\b(\s|.+){1,}\bhttp2\b|\bhttp2\b(\s|.+){1,}\bssl\b).*;" "$conf")
else
	if version_ge "$(nginx -v 2>&1 | cut -d'/' -f2)" "1.25.1"; then
		echo "http2 on;" > /etc/nginx/conf.d/http2-directive.conf

		while IFS= read -r old_param; do
			new_param="$(echo "$old_param" | sed 's/\shttp2//')"
			sed -i "s/$old_param/$new_param/" "$conf"
		done < <(grep -E "listen.*(\bssl\b(\s|.+){1,}\bhttp2\b|\bhttp2\b(\s|.+){1,}\bssl\b).*;" "$conf")
	else
		listen_ssl="$(grep -E "listen.*\s\bssl\b(?:\s)*.*;" "$conf")"
		listen_http2="$(grep -E "listen.*(\bssl\b(\s|.+){1,}\bhttp2\b|\bhttp2\b(\s|.+){1,}\bssl\b).*;" "$conf")"

		if [ -n "$listen_ssl" ] && [ -z "$listen_http2" ]; then
			while IFS= read -r old_param; do
				new_param="$(echo "$old_param" | sed 's/\sssl/ ssl http2/')"
				sed -i "s/$old_param/$new_param/" "$conf"
			done < <(grep -E "listen.*\s\bssl\b(?:\s)*.*;" "$conf")
		fi
	fi
fi
```

**Comment by myrevery** [comment]
One more small request.

Could you please revert the changes to templates in this PR and #3695?

Cause #3692 will update all templates, I can remove the "listen ... http2" parameter by the way, just to avoid a whole bunch of merge conflicts, if you will...

Thanks!

**Comment by jaapmarcus** [comment]
I rebased the RTT PR on the current main branch and resolved that way the merge conflicts. For this PR feel free to create a new PR as it hasn't been merged yet and we will close this one...

With the exception of v-add-sys-ip and add_mail_conf  it should be fine.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3703

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3704

**Pull request closed without merging**
