### PR TITLE
Implement basic support for SSHFP DNS records

### PR DESCRIPTION
**Pull request by ghost**
This allows them to be manually added. It also includes automatic generation of the records when the dns zone is first created.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Thank you for your contribution!

However got some issues when I used the branch

Jul 23 13:31:55 dev.domain.eu named[607]: dns_rdata_fromtext: /home/bsp/conf/dns/domain.nl.db:22: not a valid number
Jul 23 13:31:55 dev.domain.eu named[607]: zone domain.nl/IN: loading from master file /home/bsp/conf/dns/domain.nl.db failed: not a valid number
Jul 23 13:31:55 dev.domain.eu named[607]: zone domain.nl/IN: not loaded due to errors.
Jul 23 13:31:55 dev.domain.eu named[607]: dns_rdata_fromtext: /home/eris/conf/dns/domain.nu.db:22: not a valid number
Jul 23 13:31:55 dev.domain.eu named[607]: zone domain.nu/IN: loading from master file /home/eris/conf/dns/domain.nu.db failed: not a valid number
Jul 23 13:31:55 dev.domain.eu named[607]: zone domain.nu/IN: not loaded due to errors.

Line 22 
 @	14400	IN	SSHFP		"1 2 43898e00f660604ea7fb1226742583246ebbab66867adb269c2aaee7bfb0f0d8"
@	14400	IN	SSHFP		"2 2 3b0af9ded0dbd231534c5f8f211a6b0904a8b4e57e5e4956b1e0373ad54e8102"
@	14400	IN	SSHFP		"3 2 4b42772e6886589e7159a4c21d1d287439dcadc086dd288ea98bc2cc0cb74260"
@	14400	IN	SSHFP		"4 2 31e0e4f94df10aa6e63d0fde82e995ebd85e0181dffff38ed8d7beac188305ce"

**Comment by ghost** [comment]
Redid my changes into a single commit to simplify the divergence issues that had come up.

**Comment by jaapmarcus** [comment]
Just checked it seem to work fine.

**Comment by ghost** [comment]
For SSHFP records to be effective, DNSSEC support must also be implemented. Would you be interested in looking at this @braewoods? This would close issue #786.

**Comment by ghost** [comment]
@kristankenney I was planning on it already. But I was waiting for this to be accepted first. This can be implemented without DNSSEC but it won't be 100% effective until it is.

**Comment by ghost** [comment]
@braewoods if you can please implement DNSSEC alongside this we can go ahead and merge them for the next feature release.

**Pull request closed without merging**
