### PR TITLE
added missed block

### PR DESCRIPTION
**Pull request by anvme**

### CODE REVIEW

**Review by ScIT-Raphael — APPROVED** [review]

**Comment by anvme** [comment]
@ScIT-Raphael hello
I also added one more change
Please, review it too

**Review by jaapmarcus — COMMENTED** [review]
About https://github.com/hestiacp/hestiacp/pull/2088/commits/631677d2db2f2e0a87392217bf34a91b940c41ea

I don't think we use these file any more. It probably makes sense to delete them if not used any more. As It is only legacy code...

**Comment by anvme** [comment]
I need some help with commit 32d632b
Can't understand, how to use the value from config and set it to crontab file with sed. 
I want to create sh and run it on change or adding value in config. Where to set it and how to run it?
P.S. Start was here https://forum.hestiacp.com/t/proposal-hestiacp-zabbix-agent-process-monitoring-proc-num-0/4246

**Comment by jaapmarcus** [comment]
Please create a new branch and then the  pull request for it. I prefer the pull requests to 1 topic instead as it makes easier reviews possible. And they are free... So who cares.

**Comment by anvme** [comment]
> Please create a new branch and then the pull request for it. I prefer the pull requests to 1 topic instead as it makes easier reviews possible. And they are free... So who cares.

Ok, I revert changes

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
