### PR TITLE
Remove uneccessary modifications to sshd_config

### PR DESCRIPTION
**Pull request by vestacp-user**
Low priority code housekeeping suggestion to remove uneccessary modifications to sshd_config.  The `DebianBanner no` and `LoginGraceTime 1m` are probably old legacy code and really don't do anything usefull.  The highly critical sshd_config file should be modified the least possible.  

`DebianBanner no` is against the protocol rules and security by obscurity doesn't work because there are other ways to infer the sshd version.   It could also lead to unexepected problems. The default has always been and still is `DebianBanner yes` in Debian 10 Buster and Ubuntu 20.04LTS

Reference: `man sshd_config`

Less code is also easier to maintain and audit.

### CODE REVIEW

**Review by tlcd96 — CHANGES_REQUESTED** [review]
why are you removing the code? instead of removing, make an condition in the installer, since hestia supports other versions of the os's

**Comment by vestacp-user** [comment]
@skullwritter I explained why in my pull. This applies for all OSes that use `sshd` and `sshd_config`. 

This pull actually increases the chances that the installer will work for more OSes since it let's the OS decide what settings are best for the sshd_config instead of it being forced by the installer.  Additionally, as I explained, the `DebianBanner no` is against the protocol rules, non-standard and also not the default for most OSes.  Leaving it at it's natural state will decrease the chance of other OSes having problems with the installer and subsequent operations.

**Comment by tlcd96** [comment]
@vestacp-user if it does not have any problem with older os's that hestiacp supports, improves security and bug risk, then it's a go for me. thanks for the clarification.

**Comment by ioannidesalex** [comment]
Please also have in mind that whatever change we do, we need to apply it via updater scripts to current installations as well, in order to keep consistency.

**Comment by vestacp-user** [comment]
@ioannidesalex During future upgrades from 1.2.0 (current release), I really don't suggest modifying the sshd_config on existing installs.  This pull is really just for future fresh installs, and to help Hestia reduce it's long term code maintenance responsibility and increase compatibility across future distros and distros releases.

In respects to this pull specifically, existing installs would retain the sshd_config file as it currently is for `DebianBanner no` and `LoginGraceTime 1m`.  There is very little benefit in touching the sshd_config file on existing installs, but there is a high risk. 

If you still wish to have a change in the upgrade script, I can provide the pull.

**Review by ioannidesalex — CHANGES_REQUESTED** [review]
- I am not in favour of setting/increasing LoginGraceTime to the default (2m).

- Regarding DebianBanner, I agree it's obsolete.

- I am in favour of keeping systems consistent, thus any change should be applied to current installations as well via the update scripts.

**Comment by vestacp-user** [comment]
Relaced by #1008

**Comment by vestacp-user** [comment]
Replaced by #1008

**Pull request closed without merging**
