### PR TITLE
Update hestia-php to 8.2.0

### PR DESCRIPTION
**Pull request by jaapmarcus**
Update hestia-php to 8.2.0 

It looks to be working... 

As no major changes have been made

### CODE REVIEW

**Comment by istiak101** [comment]
https://github.com/PCRE2Project/pcre2/releases/tag/pcre2-10.42

Also this maybe?

**Comment by jaapmarcus** [comment]
Yup will update it

**Comment by jaapmarcus** [comment]
And update it

**Comment by jaapmarcus** [comment]
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/hestia/web/inc/main.php on line 453
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/hestia/web/inc/main.php on line 453
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/local/hestia/web/inc/main.php on line 457

During updating hestia package

**Review by divinity76 — APPROVED** [review]

**Comment by divinity76** [comment]
i suspect we're going to get a bunch E_DEPRECATED for dynamic properties 
 ref https://wiki.php.net/rfc/deprecate_dynamic_properties

for example in https://github.com/hestiacp/hestiacp/blob/main/install/deb/phpmyadmin/hestia-sso.php#L15 
we have
```
		$this->hostname = "https://" . API_HOST_NAME . ":" . API_HESTIA_PORT . "/api/";
```
but there is no `hostname` property declared for `class Hestia_API`, thus this is deprecated as of 8.2


luckily the <=8.1 behavior is opt-in on a per-class basis, the "proper" fix would be
```
class Hestia_API {
        private string $hostname;
	private $api_url;
```
and the lazy fix would be
```
#[AllowDynamicProperties]
class Hestia_API {
	private $api_url;
```

**Comment by jaapmarcus** [comment]
PHPmyadmin still might run on older php version as we run phpmyadmin under the default domain and not under port 8083.

But we should probally looking into feature proofing it

**Pull request merged**
