### PR TITLE
Update cn.php

### PR DESCRIPTION
**Pull request by myrevery**
Refine some details.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
@myrevery Thank you for your contribution,

We have decided to switch over to "Gettext" based system for the next release. 

There for I have already merge your changes into "https://translate.hestiacp.com/projects/hestiacp/zh-cn/default/"

 Please join Discord (https://discord.gg/nXRUZch) so I can give you access to the new system..

Best regards

**Comment by myrevery** [comment]
@jaapmarcus Thanks for your invitation,
But due to privacy concerns, I'm unwilling to register a Discord account.
I'm so sorry! 
Can we email chat?

**Comment by jaapmarcus** [comment]
No problem send me a email to xxxxxxxxx

**Comment by myrevery** [comment]
@jaapmarcus Has sent you an email.

**Comment by jaapmarcus** [comment]
I will close this pull request.

Thank you for your contribution on https://translate.hestiacp.com/projects/
👍🏻

**Pull request closed without merging**
