### PR TITLE
fix/000_allow-dots-in-ftp-username

### PR DESCRIPTION
**Pull request by jrohde**
Just a small fix for deleting/updating FTP users when using account names with a dot in it. E.g. an account called 'cooluser.com' would get a FTP username as 'cooluser.com_ftp'. Creating works, but deleting and updating the FTP user wasn't possible.

### CODE REVIEW

**Comment by jrohde** [comment]
+Also removed the - wrongly formatted - username hint for existing FTP account(s) on the web edit page; it isn't necessary displaying it at that stage, only when creating a new FTP user.

**Comment by ScIT-Raphael** [comment]
Hi @jrohde 

Thanks for your PR, we will review and merge it soon!

**Review by jaapmarcus — COMMENTED** [review]
There was still a bug in 1.3.5 where it was shown double will befixed in 1.3.5

Hint is still needed as we have changed a few things in the UI. 
Screenshot 2021-05-25 at 19 19 59

**Review by jaapmarcus — COMMENTED** [review]
We have removed the option to add / edit / remove ftp accounts on the "add" web page

**Pull request closed without merging**
