### PR TITLE
Update panel.html

### PR DESCRIPTION
**Pull request by SCelik**
Better display for usernames.

If you chose a short usernames for users, due to restrictions, it will give more descriptive information.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Could cause issues with longer usernames:

Screenshot 2020-12-11 at 10 21 54
Screenshot 2020-12-11 at 10 24 32

**Comment by ScIT-Raphael** [comment]
Hi @SCelik 

Thanks for the pr! We just discussed and tested it in our dev chat - if we use the name field, there are possibilitys that the name field will be to long - at least when I would use my full name :).

I'll close this request for now, please feel free to comment it if you are not in the same consent.

**Comment by SCelik** [comment]
What about adding NAME into title of username?

**Comment by ScIT-Raphael** [comment]
Can you show us with a screenshot what you mean?

**Comment by SCelik** [comment]
image
image

**Comment by SCelik** [comment]
I mean html title tag.

When mouseover it'll display NAME

**Comment by Lupul** [comment]
Adding title would make sense, but using the full name as per PR is problematic as it is not unique, but username is

**Comment by jaapmarcus** [comment]
The "Admin" panel html has been updated already to support title we should pull problally both version in sync.

**Pull request closed without merging**
