### PR TITLE
Simplify parallax/fixed/sticky positioning

### PR DESCRIPTION
**Pull request by AlecRust**
This is an opinionated design change, but personally the amount of fixed/sticky positioning when scrolling feels a bit much.

In this PR I've simplified this somewhat. The main top bar remains fixed, but the rest of the content now scrolls underneath as normal. The one exception to this is the "sort bar" that contains the main submit button for the form. This remains as "sticky" to the top when scrolling down.

Any thoughts/opinions welcome! And any testing 🙂 

**Before:**

https://user-images.githubusercontent.com/247634/201533924-60b40ad0-f244-476a-bab0-4925401af6c0.mp4

**After:**

https://user-images.githubusercontent.com/247634/201533984-b05f0542-5547-4b46-8266-7207488947be.mp4

### CODE REVIEW

**Comment by jaapmarcus** [comment]
I am fine with the changes but maybe somebody else has any remarks?

**Comment by johnnyq** [comment]
@AlecRust Thank you for design work updates you have done and showing the before and after screenshots/video is very helpful.
Regarding this update I prefer the before so I know what section i'm in as I get lost without some sort of breadcrumbs.

**Comment by johnnyq** [comment]
@AlecRust 
I think a good design choice to de-clutter but still keep the breadcrumbs idea in place is:

On the very top sticky nav move everything that is currently to the right in its own dropdown user menu

and move users, web, dns, DB, mail, cron, backups on the very top sticky nav

**Comment by johnnyq** [comment]
@AlecRust Well maybe keep the notification bell on the right as well

**Comment by AlecRust** [comment]
Thanks for your feedback @johnnyq

> I prefer the before so I know what section i'm in as I get lost without some sort of breadcrumbs.

The name of the section you're in is in the page `<title>`:

image

Just to be clear, what we lose here is only visibility of these links when scrolled down the page:

image

I agree a "real" breadcrumb would be good though e.g. `Cron > Add Cron Job` above the form. Feels like a separate design change to this one.

> On the very top sticky nav move everything that is currently to the right in its own dropdown user menu, and move users, web, dns, DB, mail, cron, backups on the very top sticky nav

These sound like significant design changes. I don't have an image in my head of how this would work/look but feel free to mock something up and I can think about implementing in future. Such changes feel out of scope for this PR.

**Comment by johnnyq** [comment]
@AlecRust That is true the section is in the title although the title can get quite squished when many tabs are open.
I know the changes were out of scope, i'll open up an issue with the design changes I was thinking. I think taking off the sticky bit would be fine for that nav bar. I think it will open things up to new ideas and creativity going forward.
So I'm for this change

**Comment by AlecRust** [comment]
Sounds good @johnnyq thank you

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
