### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by hestiacn**
Request to add zh-CN.README.md link to README.md and add zh-CN.README.md file to main branch! The zh-CN.READMEmd file is here https://github.com/hestiacn/hestiacp/blob/7c7fe62919b94288a84280e426cca6bc5dd38d4a/zh-CN.README.md

### CODE REVIEW

**Comment by jaapmarcus** [comment]
It is for us impossible to control/check/validate the content.

**Comment by hestiacn** [comment]
Should I paste the content here?

**Comment by AlecRust** [comment]
Why maintain a separate fork? Just improve the translations instead? https://crowdin.com/project/hestiacp

**Comment by hestiacn** [comment]
> Why maintain a separate fork? Just improve the translations instead? https://crowdin.com/project/hestiacp

I want to add a zh-CN.README.md file to the main branch and add this link to the appropriate location in README.md.
I don't have editing rights! So GitHub automatically updated to this branch!

**Comment by AlecRust** [comment]
Yes. But why would we link to a separate fork we don't control? Why are you maintaining a fork that only changes translations?

What is hestiamb? 😄

**Pull request closed without merging**
