### PR TITLE
Bump b2 cli to latest official version

### LINKED ISSUE #2348: [Bug] Backblaze backup fail to run with /tmp noexec
### Describe the bug

For security concern, we should make /tmp noexec.
However, the B2 backup requires +x on /tmp.

### Tell us how to replicate the bug

1. Install hestiacp as a docker container (https://hub.docker.com/r/smied/hestia-cp)
2. Try running: v-backup-user admin

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface

### Hestia Control Panel Version

1.4.5

### Operating system

Ubuntu 20

### Log capture

```shell
b2: error while loading shared libraries: libz.so.1: failed to map segment from shared object
2022-01-14 10:18:22 Size: 2 MB
2022-01-14 10:18:22 Runtime: 1 minute
```

### PR DESCRIPTION
**Pull request by ptrinh**
Bump b2 cli to latest official version. This will fix the issue that Backblaze backup fail to run with /tmp noexec

### CODE REVIEW

**Comment by ScIT-Raphael** [comment]
@jaapmarcus I'll review it tomorrow morning, it will probaly make sense - but we need to remove the existing binary during the upgrade script (if it exists), so the script will download it again.

**Comment by jaapmarcus** [comment]
It is indeed missing the upgrade script we should implement it probably the same as we did with phpmyadmin or any other package that we install

**Review by jaapmarcus — CHANGES_REQUESTED** [review]
Missing upgrade path for current install + When updates are released in the future..

**Review by ptrinh — COMMENTED** [review]
Updated the upgrade path

**Pull request merged**
