### PR TITLE
Release Hestia v1.3.3

### PR DESCRIPTION
**Pull request by ScIT-Raphael**

### CODE REVIEW

**Comment by vvcares** [comment]
Hi, Im waiting for my hestia to be auto-update itself ( as usual previous editions). Even i tried manually trigger the update hestia via /list/updates/.. Nothing happens. Any advise..

**Comment by jaapmarcus** [comment]
apt update && apt upgrade ?

**Comment by vvcares** [comment]
Ubuntu Linux 20.04.1 with 2GB real memory & 2GB virtual memory
Current Hestia v1.3.2

nothing happens. 
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by ScIT-Raphael** [comment]
Did you upgraded from 18.04 to 20.04?

**Comment by vvcares** [comment]
Hi, yes, i did manual upgraded from 18.04 to 20.04, on about 2 months earlier..
Got some issues about libzip5 and i resolved by manually installed them too. After that, Hestia has no issues at all for v1.3.2
Now trying for v1.3.3

**Comment by ScIT-Raphael** [comment]
Check your sources in /etc/apt/sources.list.d/ and uncomment them. They get disabled on OS upgrade, but you will be informed during the upgrade process. Also adjust them to the new os name to be sure, you're up to date.

**Comment by vvcares** [comment]
in /etc/apt/sources.list.d/, i dont see anything related to LIBZIP. Kindly advise what command line should be added into sources.list.d?

**Comment by jaapmarcus** [comment]
There should be a line for HestiaCP

**Comment by tudorr89** [comment]
`nano /etc/apt/sources.list.d/hestia.list` and add `deb https://apt.hestiacp.com/ focal main`
then
`apt update && apt upgrade` and you should be fine

**Comment by ScIT-Raphael** [comment]
what @tudorr89 wrote, but also check files for nginx.conf and mariadb/mysql.conf.

**Comment by tudorr89** [comment]
@ScIT-Raphael I had a similar issue after upgrading from 18.04 to 20.04, but in my case the hestia repository was commented rather than missing at all. So, @vvcares  also make sure all other apt sources exist and they are NOT commented out!

**Comment by vvcares** [comment]
@tudorr89 & @ScIT-Raphael 
Success. I just added hestia repo line and upgrade success.
nginx.conf & mysql.conf files are exists. My sites with mysql are works well. I will monitor more.. 
Thank you..

**Pull request merged**
