### PR TITLE
unicode characters in shell arguments (composer solution)

### PR DESCRIPTION
**Pull request by divinity76**
a composer-based alternative to PR https://github.com/hestiacp/hestiacp/pull/2717

patched in with this script:
```php
<?php
declare(strict_types=1);
$dir = "/home/hans/projects/hestiacp";
foreach ((new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir, RecursiveDirectoryIterator::SKIP_DOTS))) as $file) {
    /** @var SplFileInfo $file */
    $path = $file->getRealPath();
    $ext = strtolower($file->getExtension());
    if($ext !== "php"){
        continue;
    }
    $content = file_get_contents($path);
    $lines = explode("\n", $content);
    if(false === stripos($content, "escapeshellarg")){
        continue;
    }
    $lastUseLine = null;
    $lastDeclareLine = null;
    $firstPhpLine = null;
    foreach($lines as $lineno => $line){
        if($firstPhpLine === null && preg_match('/^\s*<\?php/', $line)){
            $firstPhpLine = $lineno;
        }
        if(preg_match("/^\s*use\s+/i", $line, $matches)){
            $lastUseLine = $lineno;
        }
        if(preg_match("/^\s*declare\s*\(/i", $line, $matches)){
            $lastDeclareLine = $lineno;
        }
    }
    if($firstPhpLine === null){
        echo "wtf couldn't find phpline in {$path} !";
        continue;
    }
    if($lastUseLine === null && $lastDeclareLine === null){
        $lines[$firstPhpLine].="\nuse function Divinity76\quoteshellarg\quoteshellarg;";
    } elseif($lastUseLine !== null){
        $lines[$lastUseLine].="\nuse function Divinity76\quoteshellarg\quoteshellarg;";
    } elseif($lastDeclareLine !== null){
        $lines[$lastDeclareLine].="\nuse function Divinity76\quoteshellarg\quoteshellarg;";
    } else {
        throw new \LogicException("unreachable");
    }
    $content = implode("\n", $lines);
    $content = strtr($content, [
        "escapeshellarg" => "quoteshellarg",
    ]);
    file_put_contents($path, $content, LOCK_EX);
}
```
- manually reverted the test/make-test-containers.php changes, not sure what to do with that one because it doesn't have access to composer? but it's unused anyway, someone said.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Question to be asked if we want to "control" https://github.com/divinity76/phpquoteshellarg under Hestia organisation instead?

**Comment by divinity76** [comment]
@jaapmarcus no problem, cloning it to hestacp and replacing `divinity76` with `hestiacp` should suffice ^^ (btw i might add a Windows version of quoteshellarg in the future, not sure if a hestiacp repo would accept a patch for that? the code is going to be non-trivial: https://docs.microsoft.com/en-us/archive/blogs/twistylittlepassagesallalike/everyone-quotes-command-line-arguments-the-wrong-way )

**Comment by divinity76** [comment]
this PR seems to be rotting fast, just fixed 3 merge conflicts. (and git was being a pain about it)
```
fix merge conflicts

Merge branch 'main' into quoteshellarg-composer

# Conflicts:
#	install/deb/filemanager/filegator/configuration.php
#	web/download/web-log/index.php
#	web/reset/mail/index.php
```

**Comment by jaapmarcus** [comment]
> @jaapmarcus no problem, cloning it to hestacp and replacing `divinity76` with `hestiacp` should suffice ^^ (btw i might add a Windows version of quoteshellarg in the future, not sure if a hestiacp repo would accept a patch for that? the code is going to be non-trivial: https://docs.microsoft.com/en-us/archive/blogs/twistylittlepassagesallalike/everyone-quotes-command-line-arguments-the-wrong-way )

Didn't work that well let keep it as is. Need to make a few small changes due to "version" changes. Will push them soon

**Pull request merged**
