### PR TITLE
i've developed  small install scriptline builder

### PR DESCRIPTION
**Pull request by gabizz**
pure javascript+html, no frameworks, no compilation needed. seems to work ok (vestacp has one for many years now)

### CODE REVIEW

**Comment by Lupul** [comment]
Thx for your PR but it cannot be merged. You should base your changes on develop branch not on master and follow project naming conventions.

**Comment by ghost** [comment]
Hi @gabizz,

I've gone ahead and manually added in the URL to README.md on the develop branch which will soon be pushed to master as well; thanks for your time & contribution!

**Comment by gabizz** [comment]
thank you. i'm still in process of getting accustomed to work with git in a
team environment :)

**Comment by ghost** [comment]
@gabizz No problem. Take a look into GitKraken (it's free for non-commercial use and cross-platform), I use it quite a bit as it has helped considerably in using Git.

**Comment by gabizz** [comment]
thanks a lot. i'll give it a try.

**Pull request closed without merging**
