### PR TITLE
Quick install cli

### PR DESCRIPTION
**Pull request by jaapmarcus**
Based on Sympony/Console

Usage: to install Wordpress

```
v-quick-install-app install user domain WordPress password="12334" email="email@domain.com"
```

Support all Quick install apps. Will expand in the future

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Todo: 
- List support list all availble apps
- Info provide required fields

**Comment by jaapmarcus** [comment]
Usage list

```
 v-quick-install-app  options
```

Returns:
```
DokuWiki - 2023-04-04a
Drupal - latest
Flarum - latest
Grav - latest
Joomla - 5.1.1
Laravel - 10.x
MediaWiki - 1.41.1
Nextcloud - latest
OpenCart - 4.0.2.2
PrestaShop - 8.1.0
Symfony - latest
WordPress - latest
```

Usage options
```
 v-quick-install-app  options  user domain.com Drupal
```
returns

```
--username Default Value: admin Type: text
--password Default Type: password
--email Default Type: text
--php_version Default Value: 8.2 Type: select
--database_create Default Value: 1 Type: boolean
--database_name Default Value:  Type: text
--database_user Default Value:  Type: text
--database_password Default Value:  Type: password
```

**Comment by mawaki** [comment]
I got the following error with this command:

`PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Console\Application" not found in /usr/local/hestia/bin/v-quick-install-app:39
Stack trace:
#0 {main}
  thrown in /usr/local/hestia/bin/v-quick-install-app on line 39
`

**Comment by jaapmarcus** [comment]
Did you install the alpha version of 1.9?

**Comment by mawaki** [comment]
Hi @jaapmarcus,

Thanks for replying. I have not yet. Waiting on the official release since I use ubuntu. I will check later after the official release.

Thanks!

**Comment by jaapmarcus** [comment]
That will explain why it doesn't work as it is missing the changes to composer ..

**Comment by mawaki** [comment]
I installed the alpha version of 1.9, I used the command below (with personal info):

`v-quick-install-app install admin domain.com WordPress email="info@hestiacp" password="123456" username="admin" site_name="HestiaCP Demo" install_directory="/" language="nl_NL" php_version="8.2" database_create="true"`

And I got the error below:
`Required PHP version is not supported`

I then installed php 8.0 to 8.2 using the interface to make it work.

We might want to install the required php versions by default.

**Comment by mawaki** [comment]
Another one that we can look at. I tried to install Drupal and it took forever. After cancelling, below is the log.

Screenshot 2024-08-12 002550

**Comment by jaapmarcus** [comment]
> We might want to install the required php versions by default.

We never install an PHP on default this should be done by the administrator

**Comment by jaapmarcus** [comment]
> Another one that we can look at. I tried to install Drupal and it took forever. After cancelling, below is the log.
> 
> Screenshot 2024-08-12 002550

This is unrelated bug to the "CLI" Command line installer but a bug to the app it self..
https://github.com/hestiacp/hestiacp/issues

**Comment by mawaki** [comment]
Thanks @jaapmarcus !

**Comment by kalungia** [comment]
When will  version 1.9.0 be available

**Comment by mawaki** [comment]
> When will version 1.9.0 be available

https://forum.hestiacp.com/t/1-9-0-beta-1-released/16804

**Pull request merged**
