### PR TITLE
v-add-firewall-ban: Insert ban in 5th position

### PR DESCRIPTION
**Pull request by jlguerrerosanz**
So that there is space for a whitelist first.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
We should write a few test cases for this one. So we are sure it works as intended.

**Comment by jaapmarcus** [comment]
I would assume https://github.com/hestiacp/hestiacp/pull/2882 and this one go together?

**Comment by jlguerrerosanz** [comment]
Yes. This way we ensure that even manually inserted rules would go to the 5th position and respect the whutelist

**Comment by jaapmarcus** [comment]
Merged with #2882

**Pull request closed without merging**
