### PR TITLE
Extend DirectAdmin import

### PR DESCRIPTION
**Pull request by ricardo777**
Add import of 
- Cronjobs
- Domain aliases and pointers to HestiaCP domain alias

Add a switch for enabling Lets encrypt for the imported domains
Add a optional text in the user account, so we can see they are imported
Fix issue with restoring database password because Directadmin save the file with url encoding in the text

Code is tested with latest DirectAdmin version 1.664 including checking of file integrity, email login, database login etc. 

When the changes are merged, I will create a forum topic that includes a small script to automate the import of multiple DirectAdmin backup files from a specified folder.

### CODE REVIEW

**Comment by ricardo777** [comment]
Sorry about the lint issue, I have tried to run ( npx prettier --check . )the prettier myself but that has no errors to report.

**Comment by AlecRust** [comment]
@ricardo777 `prettier --check .` will not display where it needs to change. `prettier --write .` will write the necessary changes though.

**Comment by ricardo777** [comment]
@AlecRust I have run it in my windows terminal but nothing change is that normal? I have added a third commit because of an error in some database files, the commit is after running your command. I run it as:

 npx prettier --write .

because without npx it does not run.

**Comment by ricardo777** [comment]
@AlecRust Ok I think I got it now, needed some setup because of Windows. Thank you for the help.

Update. It fails again, sorry I don't get it working 😞

**Comment by AlecRust** [comment]
Yeah `npx` is fine at the front. Be sure to run it from the same directory that contains `.prettierrc.cjs` in order to pick up our config.

It's not the end of the world, the PR can be reviewed without it.

**Comment by ricardo777** [comment]
@AlecRust Ah I now see the issue, I did not have the config file setup. I now done it again now and there are no errors. Thank you for the help, really appreciate it.

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
