### PR TITLE
Fix: #4181 Checks for usernames starting with a alphabetic character.

### LINKED ISSUE #4181: php not working if a user is only numbers
### Describe the bug

After installing hestiacp an a fresh debian 11.8 and adding a User and a domain webserver delivers default index.html, but if i copy any php file over or create a info.php and wnat to open it, i get file not found. in log it says [proxy_fcgi:error] AH01071 : Got error 'Pimary script unknown'

### Tell us how to replicate the bug

1. setup debian 11.8
2. install hestia with script
3. add user 090006
4. add webdomain and check if index.html ist working
5. insert any php file (info.php for example)
6. get file not found
7. delete user
8. add user K090006
9. add webdomain and check if index.html ist working
10. insert any php file (info.php for example)
11. php is working

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.8.10

### Operating system

Debian 11.8

### Log capture

_No response_

### PR DESCRIPTION
**Pull request by Aartsie**
Added an "username starting with a alphabetic character" check to function `is_user_format_valid()`

Testing results:
```bash
root@hestia:~# bash v-add-user asdas123 test "me@xxxxxxxxx.nu"
root@hestia:~# bash v-add-user asdadaaa test "me@xxxxxxxxx.nu"
root@hestia:~# bash v-add-user 12345 test "me@xxxxxxxxx.nu"
Error: invalid user format :: 12345
root@hestia:~# bash v-add-user 12345asdasd test "me@xxxxxxxxx.nu"
Error: invalid user format :: 12345asdasd
root@hestia:~# bash v-add-user 12asdad123 test "me@xxxxxxxxx.nu"
Error: invalid user format :: 12asdad123
root@hestia:~# bash v-add-user 12asdad123aaa test "me@xxxxxxxxx.nu"
Error: invalid user format :: 12asdad123aaa
```

Closes #4181

### CODE REVIEW

**Comment by jaapmarcus** [comment]
> Debian/Ubuntu based systems enforce the regular expression ^[a-z][-a-z0-9]*$, i.e. only lower case ASCII letters, digits and hyphens. As first character only lowercase ASCII letters are allowed. This regular expression is configurable by the administrator at runtime though. This rule enforces a minimum length of one character but no maximum length.

Also:
```
root@dev:~# adduser 666
adduser: To avoid ambiguity with numerical UIDs, usernames which
            consist of only digits are not allowed.
root@dev:~# adduser 666aaa
adduser: Please enter a username matching the regular expression
            configured via the NAME_REGEX configuration variable.  Use the
            `--allow-bad-names' option to relax this check or reconfigure
            NAME_REGEX in configuration.
root@dev:~# adduser a666
```

I agree voor "user" accounts we should block both  [0-9] and [0-9][a-z] user accounts 

How ever I am not use we use the same check for localpart of emails and probally check for database username. 
As the are created like database_xxxx and xxx can be a number without any issues

**Comment by jaapmarcus** [comment]
Created some tests they will probably fail ... the first time

**Comment by Aartsie** [comment]
@jaapmarcus Do you want to change the regex to ^[a-z][-a-z0-9]*$ ?

**Comment by jaapmarcus** [comment]
> @jaapmarcus Do you want to change the regex to ^[a-z][-a-z0-9]*$ ?

No we should update it to:

^[a-zA-Z][-|\.|_[:alnum:]]{0,28}[[:alnum:]]$

The only issue now are we going to handle existing users that have been created in the past 

https://github.com/hestiacp/hestiacp/blob/b195452f713ede5cd7fd7afe53a3f7422676a49e/bin/v-add-user#L76

`useradd` accepts them but `adduser`  unless we disable the bad username check

**Comment by Aartsie** [comment]
Hi @jaapmarcus is there something I can help you with to get this merged?

**Comment by Skamasle** [comment]
Hi @Aartsie 

If this was merged in that way, this will break all current hestia users with that format.

Backup  fail

```
v-backup-user 123hdal
Error: invalid user format :: 123hdal
```

Any action in user with that format fail, add dns, add domain, add mail account:

```
 [v-add-web-domain 123hdal test.net
Error: invalid user format :: 123hdal](url)
```

If you not whant this problem, you need add this test only in v-add-user script

If you add this in func.sh you will get a lot of activity in a forum :dancers: 

You can handle this problem in this way

edit v-add-user
Add after name=$5

`FROM_V_ADD_USER=true`

Edit func.sh

And add this in is_user_format_valid() 

```
if [[ "$FROM_V_ADD_USER" == "true" ]]; then
                if ! [[ "$1" =~ ^[a-zA-Z][-|.|_[:alnum:]]{0,28}[[:alnum:]]$ ]]; then
                         check_result "$E_INVALID" "invalid $2 format :: $1"
                 fi
fi
```

In this way you can fix most issues, just need test if this working when restore backups

**Comment by jaapmarcus** [comment]
@Skamasle  agree this becomes a huge major nightmare 

Made the changes as you suggested. Will run some more tests..

**Comment by Skamasle** [comment]
@jaapmarcus Can you explain me where this fails ?

I cant reproduce issue in v-restore-user if I add FROM_V_ADD_USER=true check.

v-add-user isnt used in v-restore-user or in rebuild_user_conf function

I can restore with out errors user called 123hda

**Comment by jaapmarcus** [comment]
> @jaapmarcus Can you explain me where this fails ?
> 
> I cant reproduce issue in v-restore-user if I add FROM_V_ADD_USER=true check.
> 
> v-add-user isnt used in v-restore-user or in rebuild_user_conf function
> 
> I can restore with out errors user called 123hda

It should not fail... The only reason why the test fails was due to a bug in the restore script....  That acts sometime up when restoring users...

**Pull request merged**
