### PR TITLE
Fixes psql command in v-update-sys-rrd-pgsql

### PR DESCRIPTION
**Pull request by guicapanema**
Hi there!

While checking my postgresql logs, I found multiple instances of these lines:

```
2020-12-01 08:25:01.673 -03 [15444] postgres@postgres ERROR:  syntax error at or near "plsql" at character 1
2020-12-01 08:25:01.673 -03 [15444] postgres@postgres STATEMENT:  plsql
```

I checked the hestiacp source and found what seems to be a typo in the `v-update-sys-rrd-pgsql` command. This pull request fixes that.

Thank you so much for all the work on hestia! I'm in the process of migrating from a vesta installation and am completely amazed at all the effort you've put in on this. And it shows! User & admin experience are now so much better!

Guilherme

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Comment by guicapanema** [comment]
Hello again!

Looks like the errors continued after the first commit. I looked into it again and saw that the `sql` variable already contained the `psql` command. It ended with a `-c` parameter, after which the sql query should be passed in.

The `sql` was later prepended to `psql` again, which caused the problem.

While making these changes, I couldn't figure out if it's really necessary to pass in the database parameter (eg. `-d postgres`) as it's doing now. When trying locally, it worked both with and without the parameter, yielding different results.

```
$ psql -h localhost -U postgres -c "SELECT SUM(xact_commit + xact_rollback), SUM(numbackends) FROM pg_stat_database;"

 sum  | sum
------+-----
 1688 |   1
```

```
$ psql -h localhost -U postgres -d postgres -c "SELECT SUM(xact_commit + xact_rollback), SUM(numbackends) FROM pg_stat_database;"

 sum  | sum
------+-----
 1690 |   1
```

I could not figure out which one we want in this command, so I kept the parameter.

**Comment by Lupul** [comment]
Thanks @guicapanema for the PR, changes look good,
could you rebase your branch on 'staging/fixes' branch ?

**Comment by guicapanema** [comment]
I'm not completely sure if I did that right, @Lupul . On my fork, I did:

```
git checkout staging/fixes
git rebase main
git push
```

Is that right?

After you changed the base branch I saw on the contribution guidelines I should've used `staging/fixes`. Really sorry about that, will pay more attention in the future.

**Comment by Lupul** [comment]
```
# checkout the branch were you have commited the changes and run these:
git rebase staging/fixes
git push --force
```

**Comment by guicapanema** [comment]
I'm absolutely lost here. When I tried doing that it somehow added other people's commits to my pull request... I think that's because I commited my changes to the main branch.

I'm sorry, but I'm a bit of a newbie working on shared git repositores. Maybe it'd be easier if I closed this pull request and opened another one commiting directly to the stating/fixes branch? Would that be OK?

**Comment by Lupul** [comment]
sure, you can close this pr and open another that is based on the fixes branch

**Pull request closed without merging**
