### PR TITLE
Create Backups using Backblaze B2 Cloud

### PR DESCRIPTION
**Pull request by sexymeow**
**With these changes you can add different cron jobs, making it possible to backup daily and monthly at the same time for example, with cron1 and cron2.**

**1st:**
Install python module "b2"

`pip install b2
`

**2nd:**
Create $HESTIA/conf/b2.backup.conf contains

```
BUCKET=<bucket_name>
B2_KEYID=<Application_Key_ID>
B2_KEY=<key>
```
Desktop_screenshot

**3rd:**
Edit your CLI files as the following: [FILES](https://github.com/sexymeow/hestia/pull/1/files)

**Let's say you want to have daily backups, or weekly, and monthly. You can backup to 2 different buckets, making a CRON task for each one!** 👍 

You can do as following,

**1st**
Create a secondary .conf file for example: b2.backupmonthly.conf

**2nd**
Create new bucket and keys for that .conf
```
BUCKET=<bucket_name>
B2_KEYID=<Application_Key_ID>
B2_KEY=<key>

```

** 3rd**
Create monthly CLI's (just duplicate the Clis, rename them, and edit the code for the new .conf file) or download the files here: https://github.com/sexymeow/hestia/pull/1/files
clis example

Now you can create a CRON 1 to backup for 1 bucket, and CRON 2 to backup to 2 buckets, you can make one backup every 3 days, and other backup monthly for example...

**Inside the Backblaze panel, you can select buckets and edit "Lifecycle Settings", that way it gets deleted every X days.
For example, I will keep:**

-every 3 days backups for 1 month (cron1);
-every month backups for 6 months (cron2);

If you want to avoid getting the /bin updated and overwritten i recommend creating new Clis for everything.
on my case i created a CLI to daily backups and a CLI to monthly backups, that way i have 2 different BUCKETS on B2 with different deletion rules.

CREDITS: This was developed by @rez0n

### CODE REVIEW

**Comment by ScIT-Raphael** [comment]
Please dont forget to say thanks to the original coder when you take over his code. In that case it was @rez0n, original sources: https://github.com/serghey-rodin/vesta/pull/1848

Thanks for the writeup, we will discuss the implementation in our dev chat.

**Comment by rez0n** [comment]
Hi, I glad to know my PR was useful for someone and even can be accepted into the HestiaCP.

**Comment by sexymeow** [comment]
@rez0n thanks <3

**Comment by sexymeow** [comment]
**If you want to avoid getting the /bin updated and overwritten i recommend creating new Clis fo everything.
on my case i created a CLI to daily backups and a CLI to monthly backups, that way i have 2 different BUCKETS on B2 with different deletion rules.**

**Comment by ScIT-Raphael** [comment]
I currently working on a clean implementation of this feature, you'll find the dev branch here: https://github.com/hestiacp/hestiacp/tree/feature/b2_backup_support

I'll close the pull request, I'll merge the code as soon as it is ready.

**Pull request closed without merging**
