### PR TITLE
Exim add custom ratelimits by user

### PR DESCRIPTION
**Pull request by madito**

### CODE REVIEW

**Comment by jaapmarcus** [comment]
To do: Missing update path from current installs. Config it self looks fine

**Comment by jlguerrerosanz** [comment]
Thank you madito. Very important feature.

**Comment by kpapad904** [comment]
This is a very important feature, thank you!

I would suggest also adding a **per-domain default limit**, something between the HestiaCP system-wide default for all users of all hosted domains (`/etc/exim4/limit.conf`) and the per-user limit of this domain (`/etc/exim4/domains/$sender_address_domain/limits/$sender_address`).

So the L136 in Exim4 config would need to also read `/etc/exim4/domains/$sender_address_domain/limits/0-default` (note: I like this naming convention `0-...` , because it shows up first when doing ls but feel free to choose any name  you feel is best).

PS: A secondary feature would be to lift those rate limits for the emails exchanged between users of the same domain, but this is less important.

**Comment by madito** [comment]
> This is a very important feature, thank you!
> 
> I would suggest also adding a **per-domain default limit**, something between the HestiaCP system-wide default for all users of all hosted domains (`/etc/exim4/limit.conf`) and the per-user limit of this domain (`/etc/exim4/domains/$sender_address_domain/limits/$sender_address`).
> 
> So the L136 in Exim4 config would need to also read `/etc/exim4/domains/$sender_address_domain/limits/0-default` (note: I like this naming convention `0-...` , because it shows up first when doing ls but feel free to choose any name you feel is best).
> 
> PS: A secondary feature would be to lift those rate limits for the emails exchanged between users of the same domain, but this is less 

Hi, there are two types of limits, the one that exists by default (for all users) and the one that is established for each user, I think that specifying by domain does not provide much functionality, since in reality you can achieve it with the other two values.  

I would not eliminate the limit even if it is from the same domain due to possible malicious uses (such as malware), if you need two users (whether or not they are from the same domain) to be able to send a large number of emails, you can use the limits of each one!

**Comment by jlguerrerosanz** [comment]
Hello @madito although you are right and with the limits per user is enough, the limit per domain may come handy for sysadmins with a different opinion.

Would it be possible to include them but commented by default? 

This way everyone gets the solution they need.

**Comment by kpapad904** [comment]
> specifying by domain does not provide much functionality, since in reality you can achieve it with the other two values.

Sure you can achieve the same by creating a limit-file for every domain user separately.

But imagine 2 domains with very different needs but hosted on the same HestiaCP server:
1. a museum with 50 users, 45 that normally only receive and rarely/never send an email, and a secretary that can occasionally send 100s emails (for an event)
2. a web design agency with 5 users that might send/receive emails all day

Then you would have to list each of the 45 museum users separately with a low limit to achieve the same result (to avoid issues if one of them gets a malware and starts sending out).

PS: Anyway, it's not a big deal, I can add this feature for myself ...

**Comment by jaapmarcus** [comment]
> > specifying by domain does not provide much functionality, since in reality you can achieve it with the other two values.
> 
> Sure you can achieve the same by creating a limit-file for every domain user separately.
> 
> But imagine 2 domains with very different needs but hosted on the same HestiaCP server:
> 
> 1. a museum with 50 users, 45 that normally only receive and rarely/never send an email, and a secretary that can occasionally send 100s emails (for an event)
> 2. a web design agency with 5 users that might send/receive emails all day
> 
> Then you would have to list each of the 45 museum users separately with a low limit to achieve the same result (to avoid issues if one of them gets a malware and starts sending out).
> 
> PS: Anyway, it's not a big deal, I can add this feature for myself ...

It is is easy to set a default "email" limit on a mail domain or user . And take that limit when editing the account  as default value....

So server level default value = 50 / hr
When you create an new user it will take the 50 mail / hr limit but you can change it 
And when creating the mail account it will take the user limit (if set) or the server limit

**Comment by kpapad904** [comment]
> It is is easy to set a default "email" limit on a mail domain or user . And take that limit when editing the account as default value....

I'm trying to address the scenario of hosting domains with very different email usage patterns on the same HestiaCP server, without the need to create / edit `/etc/exim4/domains/$sender_address_domain/limits/$sender_address` for tens of users.

Maybe I'm missing something obvious here, otherwise I'll just implement it for myself, no biggie :-D

**Comment by jaapmarcus** [comment]
> > It is is easy to set a default "email" limit on a mail domain or user . And take that limit when editing the account as default value....
> 
> I'm trying to address the scenario of hosting domains with very different email usage patterns on the same HestiaCP server, without the need to create / edit `/etc/exim4/domains/$sender_address_domain/limits/$sender_address` for tens of users.
> 
> Maybe I'm missing something obvious here, otherwise I'll just implement it for myself, no biggie :-D

Server level: 10 / hr
For user: "museum" keep it 
mike@museum.org  and every body else will have limit to 10 / hr
reception@museum.org can be set to 500 / hr for the mass mailings 
And user "webdesing" set default to 200 / hr  and all accounts will have the same value (Or any thing else)

And when you set it update on museum to 20 email / hr it will update them ....

**Comment by kpapad904** [comment]
> > Maybe I'm missing something obvious here, otherwise I'll just implement it for myself, no biggie :-D
> 
> Server level: 10 / hr For user: "museum" keep it
>And user "webdesing" set default to 200 / hr and all accounts will have the same value (Or any thing else) 
> And when you set it update on museum to 20 email / hr it will update them ....

Apparently I was missing something ... Where exactly (path/file) is the default limit value for domains "webdesign" and "museum" stored?

**Comment by kpapad904** [comment]
FWIW here is an (untested) snippet where all rate limits are kept in a single file:
```
# Keep authenticated users under control
deny authenticated = *
     set acl_c_msg_limit=${lookup{$sender_address}nwildlsearch{/etc/exim/send_limits}}
     ratelimit = $acl_c_msg_limit / 1d / strict / $authenticated_id
```

/etc/exim/send_limits
```
# Commented lines and blank lines are ignored
# Format is     EMAIL: LIMIT
user1@domain1.com: 100
user2@domain1.com: 200
user3@domainXX.com: 100

# Must be the last line, this is the default limit
*@*: 50
```

Source: https://serverfault.com/questions/636804/rate-limit-exim-per-user-basis

**Comment by jaapmarcus** [comment]
Current "method" are hard to backup and hard changeable via web UI

In /etc/exim4/domains/{domain}/passwd  user data is saved in:

```
root:{MD5}$1$lLHnHK3S$mCOrYr1jdmHKnn.iJfstE.:admin:mail::/home/admin:0:userdb_quota_rule=*:storage=0M
```

We just can add:

```
root:{MD5}$1$lLHnHK3S$mCOrYr1jdmHKnn.iJfstE.:admin:mail::/home/admin:0:userdb_quota_rule=*:storage=0M:rate_limit
```

And fetching the  rate limit of the user via:

```
${extract{9}{:}{${lookup{$local_part}lsearch{/etc/exim4/domains/$domain/passwd}}}}M
```

**Comment by madito** [comment]
> FWIW here is an (untested) snippet where all rate limits are kept in a single file:
> 
> ```
> # Keep authenticated users under control
> deny authenticated = *
>      set acl_c_msg_limit=${lookup{$sender_address}nwildlsearch{/etc/exim/send_limits}}
>      ratelimit = $acl_c_msg_limit / 1d / strict / $authenticated_id
> ```
> 
> /etc/exim/send_limits
> 
> ```
> # Commented lines and blank lines are ignored
> # Format is     EMAIL: LIMIT
> user1@domain1.com: 100
> user2@domain1.com: 200
> user3@domainXX.com: 100
> 
> # Must be the last line, this is the default limit
> *@*: 50
> ```
> 
> Source: https://serverfault.com/questions/636804/rate-limit-exim-per-user-basis

What you have proposed was very similar to the first implementation that was done in my PR, but it is difficult to make backups or separate by domains, that is why modifications were made until the implementation of the last commit was achieved.

**Comment by madito** [comment]
> Current "method" are hard to backup and hard changeable via web UI
> 
> In /etc/exim4/domains/{domain}/passwd user data is saved in:
> 
> ```
> root:{MD5}$1$lLHnHK3S$mCOrYr1jdmHKnn.iJfstE.:admin:mail::/home/admin:0:userdb_quota_rule=*:storage=0M
> ```
> 
> We just can add:
> 
> ```
> root:{MD5}$1$lLHnHK3S$mCOrYr1jdmHKnn.iJfstE.:admin:mail::/home/admin:0:userdb_quota_rule=*:storage=0M:rate_limit
> ```
> 
> And fetching the rate limit of the user via:
> 
> ```
> ${extract{9}{:}{${lookup{$local_part}lsearch{/etc/exim4/domains/$domain/passwd}}}}M
> ```


The current method saves limits on:

/etc/exim4/domains/$sender_address_domain/limits/$sender_address —> users custom

/etc/exim4/limit.conf —> default

For easy backups and modification from UI.

**Comment by kpapad904** [comment]
> And fetching the rate limit of the user via:
> 
> ```
> ${extract{9}{:}{${lookup{$local_part}lsearch{/etc/exim4/domains/$domain/passwd}}}}M
> ```

Of all the approaches considered so far, I like this one the best. Both conceptually and for its ease of integration into the current model.

I would still add a more powerful global limit file as fallback, like the (untested) one I quoted yesterday in https://github.com/hestiacp/hestiacp/pull/2225#issuecomment-1030505167  (instead of a limit file that contains just a number)

**Comment by ram108** [comment]
This fix contains only the block
`# Limit per email account for SMTP authenticated users
`

But does not contain
`# Limit per user for PHP scripts`

Therefore PHP scripts will also be configured globally, but not with `/etc/exim4/send-limits.conf`

**Comment by madito** [comment]
> 

Personally I think that modifying the PHP limits is quite insecure, whoever needs to do it, can edit the configuration file quickly.

**Comment by jaapmarcus** [comment]
Did some extensive testing:

When using:
/etc/exim4/domains/jaap.nl/limits/jaap@jaap.nl or
/etc/exim4/domains/jaap.nl/limits/jaap

It keeps reverting to the "General set" higer limit

With:
set acl_c_msg_limit = ${extract{5}{:}{${lookup{$sender_address_local_part}lsearch{/etc/exim4/domains/${lookup{$sender_address_domain}dsearch{/etc/exim4/domains}}/accounts}}}}

It works fine as long as I add: :10 for example after each line in the accounts file... 

Also I noticed the sed in the upgrade script doesn't work correctly it also changes the lines for php scripts and these should be kept the same...

**Comment by jaapmarcus** [comment]
Waiting for Drone after that  it will be ready for merge.

**Comment by kpapad904** [comment]
> With: set acl_c_msg_limit = ${extract{5}{:}{${lookup{$sender_address_local_part}lsearch{/etc/exim4/domains/${lookup{$sender_address_domain}dsearch{/etc/exim4/domains}}/accounts}}}}
> 
> It works fine as long as I add: :10 for example after each line in the accounts file...

But in the latest commit https://github.com/hestiacp/hestiacp/commit/8faa6b8ba9d8d80838d0b7f1f153e04a4f377764 it seems that you didn't choose the approach of adding another field into the userdb (`/etc/exim4/domains/{domain}/accounts`) with the email send limit. You chose to have a separate limit file for every user.

Didn't you like the approach of commit https://github.com/hestiacp/hestiacp/pull/2225/commits/4bc3f297e9d36ba6b4f8728f591bed4755ff4e06 from 11 days ago ?

**Comment by jaapmarcus** [comment]
I wasn't able to set up a fall back in case "user" rate limit was missing

**Pull request merged**
