### PR TITLE
Change raster logo to vector based svg

### PR DESCRIPTION
**Pull request by robothemes**
Changed raster logo to vector based svg for better compatibility with retina displays.

This is my first commit and I need to get right workflow for future work.
Feedback appreciated.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
https://imgur.com/a/viA59Ml

:heart:

**Comment by lunargrizzly** [comment]
Thanks @jaapmarcus I will fix it now. 
Forgot to check export settings for logo. It looks good to me because I have fonts installed on my system.

**Comment by jaapmarcus** [comment]
Hmm your are right did't even noticed it that the other letters where different font face.. The H is already great improvement...

**Comment by jaapmarcus** [comment]
https://imgur.com/a/g17ZrmL
❤️  ❤️ 

Even beter ("Version before vs new")

**Comment by cmstew** [comment]
Probably could compress/minify the svg too. Illustrator isn't the best at making small svg's.

**Comment by lunargrizzly** [comment]
> Probably could compress/minify the svg too. Illustrator isn't the best at making small svg's.

4kb and 11kb is not so much ;)

**Comment by cmstew** [comment]
But there is a difference. 😉 Lol Anyways, you're right. Not so bad!

Also, looks good but the way. 🎉

**Pull request merged**
