### PR TITLE
Add support of Proxmox Mail Gateway

### PR DESCRIPTION
**Pull request by 0pc0deFR**
I would like to propose this PR to add support for Proxmox Mail Gateway.

In my context, I use a PMG cluster which protects the messaging of my Hestia users.

To avoid being an open relay, PMG requires declaring all domains authorized to use it.

This PR allows you to activate and configure the necessary information on the server configuration page and allows you to automatically add/delete a domain in PMG when an email domain is added in Hestia.

Hestia Settings
image

PMG Relay Domains
image

PMG Transports
image

### CODE REVIEW

**Comment by jaapmarcus** [comment]
I am not a real fan to include an another 7 extra options for just one use case.  There are multiple other services that require  the same but slightly different. 

Maybe we we should just add an hook to v-add-mail-domain / v-delete-mail-domain that can handle all the cases so users can create their own implementation they are using?

Like we do on updating package  or updating template?

https://github.com/hestiacp/hestiacp/blob/07f0ac266528cc0dcc16e82aaca81310b0dafed5/func/rebuild.sh#L68-L71

**Comment by johnnyq** [comment]
I use Proxmox Mail Gateway for many on prem exchange platforms never thought about using it with HestiaCP
This is pretty awesome but I agree with @jaapmarcus it should absolutely be a hook and not included in the core functions

**Comment by Anuril** [comment]
I also like this Idea, but wouldn't that be a perfect fit for a plugin @jaapmarcus ? Like #4361

**Comment by coriaweb** [comment]
I like this, I also use Proxmox and I'm doing it manually.

I will try it. I assume that when updating Hestia, all changes are lost, right?

**Comment by simonzhekoff** [comment]
How can this be used? I put the files in the respective folder, but then what?

**Pull request closed without merging**
