### PR TITLE
Fix potential issue of updating to Nginx 1.21.0

### PR DESCRIPTION
**Pull request by myrevery**
My customer reported this issue, and I have also seen reports from some people on the issue list and forum, so this should help.

But this is only a temporary measure.

I'm already working on a thorough solution, I will share it when it is perfected.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Please note better solution is off course read and don't  overwrite your config file

**Comment by vvcares** [comment]
Ubuntu 20.04
Hestia 1.4.2

Hi @jaapmarcus. Is this issue settled?

I have the same issue after nginx upgrade to 1.21.x. All my website down.
I checked my hestia installation file, it contains your merged script too. 
I re run
_bash /usr/local/hestia/install/upgrade/versions/1.4.2.sh_

Even i rebooted my whole server, still all my sites down excep hestia admin panel.

**Comment by jaapmarcus** [comment]
You have to make sure you source the "hestia"  sonf. 

cp -f $HESTIA/install/deb/nginx/nginx.conf /etc/nginx/

should work

**Comment by ioannidesalex** [comment]
Did you overwrite /etc/nginx/nginx.conf and /etc/nginx/conf.d/default when prompted by apt updating nginx "with new version"? If yes that's the reason. You shouldn't do that.

Other than that, I am now using nginx 1.21 in various servers without an issue.

**Comment by myrevery** [comment]
This script is only for Hestia update, manual execution is invalid.

Just in case someone comes here find solution, run commands:

`export WEB_SYSTEM="nginx"; bash /usr/local/hestia/install/upgrade/versions/1.4.2.sh`

Then run command to test Nginx configuration:
`nginx -t`

If no errors, run command to restart Nginx:
`systemctl restart nginx`

**Comment by vvcares** [comment]
> This script is only for Hestia update, manual execution is invalid.
> 
> Just in case someone comes here find solution, run commands:
> 
> `export WEB_SYSTEM="nginx"; bash /usr/local/hestia/install/upgrade/versions/1.4.2.sh`
> 
> Then run command to test Nginx configuration:
> `nginx -t`
> 
> If no errors, run command to restart Nginx:
> `systemctl restart nginx`

_Simply.. It works man._
Upvote for you. 💯 
Thank you...

**Pull request merged**
