### PR TITLE
Rebuild top bar for mobile

### PR DESCRIPTION
**Pull request by AlecRust**
**Mobile:**
image

**Before:**
image

**After:**
image

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Comment by jaapmarcus** [comment]
I am still a fan to rewrite this part... Still the worst part for UI personally...

**Comment by tlcd96** [comment]
I'm not a fan of this design...

**Comment by tlcd96** [comment]
let me see what i can do for this... i'll take some time for it, but it's ok

**Comment by ScIT-Raphael** [comment]
its hard to do something "good" on the old vesta code base. If we want to do so, we would basicly need a complete rewrite, until then, every optimization is welcome.

**Comment by tlcd96** [comment]
i know, i can make a menu and the user account out of that and the hestiacp logo on the center. i just need to figure it out how i'm gonna do this... again

**Comment by ScIT-Raphael** [comment]
please feel free to provide a PR.

**Comment by tlcd96** [comment]
i'll do it when i'm finished

**Comment by jaapmarcus** [comment]
> I'm not a fan of this design...

Me either but it still better than nothing...

**Comment by AlecRust** [comment]
Goal of this PR was only to lay mobile-first foundations for this header, as there was no mobile support at all before.

Whatever was simplest is what I went for here. Refinements will occur in following PRs, please feel free to help with this.

**Pull request merged**
