### PR TITLE
PHP 8.2 support

### PR DESCRIPTION
**Pull request by codejp3**
Testing out PHP 8.2 support.

So far so good. Let me know if you want me to change anything else!

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Changes look fine how ever we do have a "policy" to release it only after php8.2 has been released

**Comment by codejp3** [comment]
> Changes look fine how ever we do have a "policy" to release it only after php8.2 has been released

Well, at least this will be ready to go when the time comes! Changing from draft to review. Fee free to merge when we actually get an official php8.2 release.

**Review by RealSollyM — APPROVED** [review]
Looks good to me. I can't wait to upgrade to 8.2 and test it fully.

**Comment by tlcd96** [comment]
# November 24, 2022
PHP 8.2 will be released on November 24, 2022. 
see [PHP site info](https://wiki.php.net/todo/php82)
or this [blogpost](https://stitcher.io/blog/new-in-php-82)

**Review by tlcd96 — COMMENTED** [review]
Appears to be ok

**Comment by vikasprogrammer** [comment]
Happy to sponsor to get this merged.

**Comment by jaapmarcus** [comment]
This will get merged after 8.2 has been released. How ever the are still in RC fase

Releasing and merging will take not that much time.

**Comment by vikasprogrammer** [comment]
Actually we have a need for PHP 8.2 RC at our end. So, wanted to try it out and when the final release is out, we can just upgrade. But I guess that will be too messy.

**Comment by codejp3** [comment]
> Actually we have a need for PHP 8.2 RC at our end. So, wanted to try it out and when the final release is out, we can just upgrade. But I guess that will be too messy.

FWIW, I manually installed 8.2 through apt-get. Works just fine on it's own. Just make sure you also install all the php packages you want, like imagik, zip, pdf, etc. The only reason I made these changes to Hestia is so that it displayed properly in the web interface and Hestia "v-" commands related to php worked. It's all from the same php repo, so upgrades will be smooth as butter once 8.2 is officially released and supported by Hestia.

**Comment by jaapmarcus** [comment]
```
git clone https://github.com/jaapmarcus/hestiacp.git
cd hestiacp 
git checkout php82
cd src
./hst_autocompile.sh --hestia --install '~localsrc'
dpkg -i /tmp/hestia-src/deb/hestia-*.deb
```
Temp folder maybe different

Should also do the trick

**Comment by vikasprogrammer** [comment]
Thanks @jaapmarcus and @codejp3

**Comment by tlcd96** [comment]
# December 8 2022
## new release date
see: https://wiki.php.net/todo/php82

**Review by jaapmarcus — APPROVED** [review]

**Comment by vikasprogrammer** [comment]
are you going to release a minor update tomorrow ?

**Comment by jaapmarcus** [comment]
Yes

**Comment by vikasprogrammer** [comment]
We have updated the system with `v-update-sys-hestia-all` but PHP 8.2 is not installed. 

```
 v-list-sys-hestia-updates 
PKG           VER     ARCH   UPDT  DATE
---           ---     ----   ----  ----
hestia        1.6.14  amd64  yes   2022-12-12
hestia-php    8.1.12  amd64  yes   2022-12-12
hestia-nginx  1.23.2  amd64  yes   2022-12-12
```

**Comment by ScIT-Raphael** [comment]
you need to manualy install it over v-add-web-php 8.2 or server settings...

**Comment by jaapmarcus** [comment]
> We have updated the system with `v-update-sys-hestia-all` but PHP 8.2 is not installed.
> 
> ```
>  v-list-sys-hestia-updates 
> PKG           VER     ARCH   UPDT  DATE
> ---           ---     ----   ----  ----
> hestia        1.6.14  amd64  yes   2022-12-12
> hestia-php    8.1.12  amd64  yes   2022-12-12
> hestia-nginx  1.23.2  amd64  yes   2022-12-12
> ```

We have not update hestia-php yet so it should be fine. We will update when we have time to do some test builds

**Comment by vikasprogrammer** [comment]
Is there a way to install PHP 8.2 in the meantime on our systems?

**Comment by vikasprogrammer** [comment]
Sorry just read the other comment about `v-add-web-php`.

**Comment by jaapmarcus** [comment]
hestia-php is for the backend only and is not used for CLI / Websites at all. So it should not be an issue. VestaCP still runs 5.6.x for example

**Comment by codejp3** [comment]
Thanks for the merge! Deleting branch now.

Enjoy official PHP 8.2 integration everyone!

**Pull request merged**
