### PR TITLE
add web domain wildcard alias test

### PR DESCRIPTION
**Pull request by YVbakker**
As requested by Robert Zollner in
https://discord.com/channels/737721354937303161/738055454285889597/804455409406574654

### CODE REVIEW

**Comment by Lupul** [comment]
The wildcard char *  is best to have it quoted like this: "*.$domain"

**Comment by YVbakker** [comment]
Tested on the cli of a test environment successfully without quotes - or is this related to the way bat scripts are interpreted? Can't test that on unix

**Comment by Lupul** [comment]
Without quotes, the '*' char can be used for bash globbing, ex:

image

**Comment by YVbakker** [comment]
Did test on the cli of a test hestia instance, but overlooked that bats is interpreted by bash. Fixed

**Comment by jaapmarcus** [comment]
Did a test run now:

✓ WEB: Add web domain alias 
 ✓ WEB: Add web domain alias (duplicate) 
 ✓ WEB: Add web domain wildcard alias

**Pull request merged**
